import { MigrationInterface, QueryRunner } from 'typeorm';

export class retypeUserDates1651843397008 implements MigrationInterface {
  name = 'retypeUserDates1651843397008';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "temporary_user" ("userId" varchar PRIMARY KEY NOT NULL, "userName" varchar NOT NULL, "displayname" varchar NOT NULL DEFAULT (''), "profileImageUrl" varchar NOT NULL DEFAULT (''), "isOnline" boolean NOT NULL DEFAULT (0), "isVIP" boolean NOT NULL DEFAULT (0), "isFollower" boolean NOT NULL DEFAULT (0), "isModerator" boolean NOT NULL DEFAULT (0), "isSubscriber" boolean NOT NULL DEFAULT (0), "haveSubscriberLock" boolean NOT NULL DEFAULT (0), "haveFollowerLock" boolean NOT NULL DEFAULT (0), "haveSubscribedAtLock" boolean NOT NULL DEFAULT (0), "haveFollowedAtLock" boolean NOT NULL DEFAULT (0), "rank" varchar NOT NULL DEFAULT (''), "haveCustomRank" boolean NOT NULL DEFAULT (0), "followedAt" varchar(30), "followCheckAt" bigint NOT NULL DEFAULT (0), "subscribedAt" varchar(30), "seenAt" varchar(30), "createdAt" varchar(30), "watchedTime" bigint NOT NULL DEFAULT (0), "chatTimeOnline" bigint NOT NULL DEFAULT (0), "chatTimeOffline" bigint NOT NULL DEFAULT (0), "points" bigint NOT NULL DEFAULT (0), "pointsOnlineGivenAt" bigint NOT NULL DEFAULT (0), "pointsOfflineGivenAt" bigint NOT NULL DEFAULT (0), "pointsByMessageGivenAt" bigint NOT NULL DEFAULT (0), "subscribeTier" varchar NOT NULL DEFAULT ('0'), "subscribeCumulativeMonths" integer NOT NULL DEFAULT (0), "subscribeStreak" integer NOT NULL DEFAULT (0), "giftedSubscribes" bigint NOT NULL DEFAULT (0), "messages" bigint NOT NULL DEFAULT (0), "extra" text)`);
    await queryRunner.query(`INSERT INTO "temporary_user"("userId", "userName", "displayname", "profileImageUrl", "isOnline", "isVIP", "isFollower", "isModerator", "isSubscriber", "haveSubscriberLock", "haveFollowerLock", "haveSubscribedAtLock", "haveFollowedAtLock", "rank", "haveCustomRank", "followedAt", "followCheckAt", "subscribedAt", "seenAt", "createdAt", "watchedTime", "chatTimeOnline", "chatTimeOffline", "points", "pointsOnlineGivenAt", "pointsOfflineGivenAt", "pointsByMessageGivenAt", "subscribeTier", "subscribeCumulativeMonths", "subscribeStreak", "giftedSubscribes", "messages", "extra") SELECT "userId", "userName", "displayname", "profileImageUrl", "isOnline", "isVIP", "isFollower", "isModerator", "isSubscriber", "haveSubscriberLock", "haveFollowerLock", "haveSubscribedAtLock", "haveFollowedAtLock", "rank", "haveCustomRank", "followedAt", "followCheckAt", "subscribedAt", "seenAt", "createdAt", "watchedTime", "chatTimeOnline", "chatTimeOffline", "points", "pointsOnlineGivenAt", "pointsOfflineGivenAt", "pointsByMessageGivenAt", "subscribeTier", "subscribeCumulativeMonths", "subscribeStreak", "giftedSubscribes", "messages", "extra" FROM "user"`);
    await queryRunner.query(`DROP TABLE "user"`);
    await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`);
    await queryRunner.query(`CREATE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("userName") `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "IDX_78a916df40e02a9deb1c4b75ed"`);
    await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`);
    await queryRunner.query(`CREATE TABLE "user" ("userId" varchar PRIMARY KEY NOT NULL, "userName" varchar NOT NULL, "displayname" varchar NOT NULL DEFAULT (''), "profileImageUrl" varchar NOT NULL DEFAULT (''), "isOnline" boolean NOT NULL DEFAULT (0), "isVIP" boolean NOT NULL DEFAULT (0), "isFollower" boolean NOT NULL DEFAULT (0), "isModerator" boolean NOT NULL DEFAULT (0), "isSubscriber" boolean NOT NULL DEFAULT (0), "haveSubscriberLock" boolean NOT NULL DEFAULT (0), "haveFollowerLock" boolean NOT NULL DEFAULT (0), "haveSubscribedAtLock" boolean NOT NULL DEFAULT (0), "haveFollowedAtLock" boolean NOT NULL DEFAULT (0), "rank" varchar NOT NULL DEFAULT (''), "haveCustomRank" boolean NOT NULL DEFAULT (0), "followedAt" varchar(24), "followCheckAt" bigint NOT NULL DEFAULT (0), "subscribedAt" varchar(24), "seenAt" varchar(24), "createdAt" varchar(24), "watchedTime" bigint NOT NULL DEFAULT (0), "chatTimeOnline" bigint NOT NULL DEFAULT (0), "chatTimeOffline" bigint NOT NULL DEFAULT (0), "points" bigint NOT NULL DEFAULT (0), "pointsOnlineGivenAt" bigint NOT NULL DEFAULT (0), "pointsOfflineGivenAt" bigint NOT NULL DEFAULT (0), "pointsByMessageGivenAt" bigint NOT NULL DEFAULT (0), "subscribeTier" varchar NOT NULL DEFAULT ('0'), "subscribeCumulativeMonths" integer NOT NULL DEFAULT (0), "subscribeStreak" integer NOT NULL DEFAULT (0), "giftedSubscribes" bigint NOT NULL DEFAULT (0), "messages" bigint NOT NULL DEFAULT (0), "extra" text)`);
    await queryRunner.query(`INSERT INTO "user"("userId", "userName", "displayname", "profileImageUrl", "isOnline", "isVIP", "isFollower", "isModerator", "isSubscriber", "haveSubscriberLock", "haveFollowerLock", "haveSubscribedAtLock", "haveFollowedAtLock", "rank", "haveCustomRank", "followedAt", "followCheckAt", "subscribedAt", "seenAt", "createdAt", "watchedTime", "chatTimeOnline", "chatTimeOffline", "points", "pointsOnlineGivenAt", "pointsOfflineGivenAt", "pointsByMessageGivenAt", "subscribeTier", "subscribeCumulativeMonths", "subscribeStreak", "giftedSubscribes", "messages", "extra") SELECT "userId", "userName", "displayname", "profileImageUrl", "isOnline", "isVIP", "isFollower", "isModerator", "isSubscriber", "haveSubscriberLock", "haveFollowerLock", "haveSubscribedAtLock", "haveFollowedAtLock", "rank", "haveCustomRank", "followedAt", "followCheckAt", "subscribedAt", "seenAt", "createdAt", "watchedTime", "chatTimeOnline", "chatTimeOffline", "points", "pointsOnlineGivenAt", "pointsOfflineGivenAt", "pointsByMessageGivenAt", "subscribeTier", "subscribeCumulativeMonths", "subscribeStreak", "giftedSubscribes", "messages", "extra" FROM "temporary_user"`);
    await queryRunner.query(`DROP TABLE "temporary_user"`);
  }

}
