import { MigrationInterface, QueryRunner } from 'typeorm';

export class initialize1573837256390 implements MigrationInterface {
  name = 'initialize1573837256390';

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`CREATE TABLE "alert" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "updatedAt" bigint NOT NULL DEFAULT 0, "name" character varying NOT NULL, "alertDelayInMs" integer NOT NULL, "profanityFilterType" character varying NOT NULL, "loadStandardProfanityList" text NOT NULL, "customProfanityList" text NOT NULL, CONSTRAINT "PK_ad91cad659a3536465d564a4b2f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_media" ("primaryId" SERIAL NOT NULL, "id" character varying NOT NULL, "b64data" text NOT NULL, "chunkNo" integer NOT NULL, CONSTRAINT "PK_f804c985d46d63b4aa87a103711" PRIMARY KEY ("primaryId"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_b0f12c32653ed88fd576d3520c" ON "alert_media" ("id") `, undefined);
    await queryRunner.query(`CREATE TABLE "alert_follow" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, CONSTRAINT "PK_5ebe16ce8204de178188ce86657" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_sub" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, CONSTRAINT "PK_2df84032428038786eba3e64b9d" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_subgift" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, CONSTRAINT "PK_85b3a2a8d2d5d0695f280ea08b8" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_host" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "showAutoHost" boolean NOT NULL, CONSTRAINT "PK_b7a197417e3f74b8167f1e0a193" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_raid" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "showAutoHost" boolean NOT NULL, CONSTRAINT "PK_af294493158ed9080aaf8d50e6c" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_tip" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "message" text NOT NULL, CONSTRAINT "PK_313dc0f16ea40ab91f84b11130b" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_cheer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "message" text NOT NULL, CONSTRAINT "PK_c9c5db6b64aaf74067b3ca46bc7" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alert_resub" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alertId" uuid, "enabled" boolean NOT NULL, "title" character varying NOT NULL, "variantCondition" character varying NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" character varying NOT NULL, "layout" character varying NOT NULL, "animationIn" character varying NOT NULL, "animationOut" character varying NOT NULL, "animationText" character varying NOT NULL, "animationTextOptions" text NOT NULL, "imageId" character varying NOT NULL, "soundId" character varying NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "message" text NOT NULL, CONSTRAINT "PK_515a6f6e066d020828dec8eae36" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "alias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "alias" character varying NOT NULL, "command" character varying NOT NULL, "enabled" boolean NOT NULL, "visible" boolean NOT NULL, "permission" character varying NOT NULL, CONSTRAINT "PK_b1848d04b41d10a5712fc2e673c" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_6a8a594f0a5546f8082b0c405c" ON "alias" ("alias") `, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_ed5fcb69444dcb0abf0a71053b" ON "alias" ("command") `, undefined);
    await queryRunner.query(`CREATE TABLE "bets" ("id" SERIAL NOT NULL, "createdAt" bigint NOT NULL, "endedAt" bigint NOT NULL, "isLocked" boolean NOT NULL DEFAULT false, "arePointsGiven" boolean NOT NULL DEFAULT false, "options" text NOT NULL, "title" character varying NOT NULL, CONSTRAINT "PK_7ca91a6a39623bd5c21722bcedd" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_df40819eb0eb71d2cc7d73cea8" ON "bets" ("createdAt") `, undefined);
    await queryRunner.query(`CREATE TABLE "bets_participations" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "username" character varying NOT NULL, "points" bigint NOT NULL, "optionIdx" bigint NOT NULL, "betId" integer, CONSTRAINT "PK_d63eab48dbb8c966ca471ee1734" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_eb26a8222f1ed29abbef861295" ON "bets_participations" ("userId") `, undefined);
    await queryRunner.query(`CREATE TABLE "cache_emotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "type" character varying(6) NOT NULL, "urls" text NOT NULL, CONSTRAINT "PK_530dad23ebf90799d570e7427e1" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_36cd5732ccfc2693662be974f9" ON "cache_emotes" ("code") `, undefined);
    await queryRunner.query(`CREATE TABLE "cache_games" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_83498942a78ff5d6309d91cf13e" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_f37be3c66dbd449a8cb4fe7d59" ON "cache_games" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "cache_titles" ("id" SERIAL NOT NULL, "game" character varying NOT NULL, "title" character varying NOT NULL, "timestamp" bigint NOT NULL, CONSTRAINT "PK_a2a0f1db2d0b215a771c14538a2" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_a0c6ce833b5b3b13325e6f49b0" ON "cache_titles" ("game") `, undefined);
    await queryRunner.query(`CREATE TABLE "carousel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order" integer NOT NULL, "type" character varying NOT NULL, "waitBefore" integer NOT NULL, "waitAfter" integer NOT NULL, "duration" integer NOT NULL, "animationInDuration" integer NOT NULL, "animationIn" character varying NOT NULL, "animationOutDuration" integer NOT NULL, "animationOut" character varying NOT NULL, "showOnlyOncePerStream" boolean NOT NULL, "base64" text NOT NULL, CONSTRAINT "PK_d59e0674c5a5efe523df247f67b" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "changelog" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, "threadId" character varying NOT NULL, "namespace" character varying NOT NULL, CONSTRAINT "PK_9d12e70193212a9f6d2c542433d" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "checklist" ("id" SERIAL NOT NULL, "isCompleted" boolean NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_e4b437f5107f2a9d5b744d4eb4c" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "commands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "command" character varying NOT NULL, "enabled" boolean NOT NULL, "visible" boolean NOT NULL, CONSTRAINT "PK_7ac292c3aa19300482b2b190d1e" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_1a8c40f0a581447776c325cb4f" ON "commands" ("command") `, undefined);
    await queryRunner.query(`CREATE TABLE "commands_responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order" integer NOT NULL, "response" character varying NOT NULL, "stopIfExecuted" boolean NOT NULL, "permission" character varying NOT NULL, "filter" character varying NOT NULL, "commandId" uuid, CONSTRAINT "PK_82930e9fe4fb34b3b47bc78b3bb" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "commands_count" ("id" SERIAL NOT NULL, "command" character varying NOT NULL, "timestamp" bigint NOT NULL, CONSTRAINT "PK_80e221b846abb1a84ab81281a7a" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_2ccf816b1dd74e9a02845c4818" ON "commands_count" ("command") `, undefined);
    await queryRunner.query(`CREATE TABLE "commands_board" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order" integer NOT NULL, "text" character varying NOT NULL, "command" character varying NOT NULL, CONSTRAINT "PK_97d1caf8485f381d176b41a1569" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "cooldown" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "miliseconds" integer NOT NULL, "type" character varying(10) NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, "lastTimestamp" bigint NOT NULL DEFAULT 0, "isErrorMsgQuiet" boolean NOT NULL, "isEnabled" boolean NOT NULL, "isOwnerAffected" boolean NOT NULL, "isModeratorAffected" boolean NOT NULL, "isSubscriberAffected" boolean NOT NULL, "isFollowerAffected" boolean NOT NULL, CONSTRAINT "PK_0f01954311dda5b3d353603c7c5" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aa85aa267ec6eaddf7f93e3665" ON "cooldown" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "cooldown_viewer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "timestamp" bigint NOT NULL, "lastTimestamp" bigint NOT NULL, "cooldownId" uuid, CONSTRAINT "PK_623cc80522fb1bb56c7b907c59f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "dashboard" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" bigint NOT NULL, CONSTRAINT "PK_233ed28fa3a1f9fbe743f571f75" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "widget" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "positionX" integer NOT NULL, "positionY" integer NOT NULL, "height" integer NOT NULL, "width" integer NOT NULL, "dashboardId" uuid, CONSTRAINT "PK_feb5fda4f8d30bbe0022f4ca804" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "duel" ("id" integer NOT NULL, "username" character varying NOT NULL, "tickets" integer NOT NULL, CONSTRAINT "PK_1575a4255b3bdf1f11398841d0d" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "givenName" character varying NOT NULL, "isEnabled" boolean NOT NULL, "triggered" text NOT NULL, "definitions" text NOT NULL, "filter" character varying NOT NULL, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_b535fbe8ec6d832dde22065ebd" ON "event" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "event_operation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "definitions" text NOT NULL, "eventId" uuid, CONSTRAINT "PK_ac1058d607aa18a9af827c36247" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_daf6b97e1e5a5c779055fbb22d" ON "event_operation" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "event_list" ("id" SERIAL NOT NULL, "event" character varying NOT NULL, "username" character varying NOT NULL, "timestamp" bigint NOT NULL, "values_json" character varying NOT NULL, CONSTRAINT "PK_1cc2e9353e9ae8acf95d976cf6f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_8a80a3cf6b2d815920a390968a" ON "event_list" ("username") `, undefined);
    await queryRunner.query(`CREATE TABLE "gallery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "data" text NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_65d7a1ef91ddafb3e7071b188a0" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "goal_group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" bigint NOT NULL DEFAULT 0, "name" character varying NOT NULL, "display" text NOT NULL, CONSTRAINT "PK_22b802b42def291fab90fdcda14" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "goal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "groupId" uuid, "name" character varying NOT NULL, "type" character varying(20) NOT NULL, "countBitsAsTips" boolean NOT NULL, "display" character varying(20) NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, "goalAmount" float NOT NULL DEFAULT 0, "currentAmount" float NOT NULL DEFAULT 0, "endAfter" character varying NOT NULL, "endAfterIgnore" boolean NOT NULL, "customizationBar" text NOT NULL, "customizationFont" text NOT NULL, "customizationHtml" text NOT NULL, "customizationJs" text NOT NULL, "customizationCss" text NOT NULL, CONSTRAINT "PK_88c8e2b461b711336c836b1e130" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_a1a6bd23cb8ef7ddf921f54c0b" ON "goal" ("groupId") `, undefined);
    await queryRunner.query(`CREATE TABLE "heist_user" ("userId" integer NOT NULL, "username" character varying NOT NULL, "points" bigint NOT NULL, CONSTRAINT "PK_0a41172961540da3de15a9d223d" PRIMARY KEY ("userId"))`, undefined);
    await queryRunner.query(`CREATE TABLE "highlight" ("id" SERIAL NOT NULL, "videoId" character varying NOT NULL, "game" character varying NOT NULL, "title" character varying NOT NULL, "timestamp" text NOT NULL, "createdAt" bigint NOT NULL, CONSTRAINT "PK_0f4191998a1e1e8f8455f1d4adb" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "how_long_to_beat_game" ("id" SERIAL NOT NULL, "game" character varying NOT NULL, "startedAt" bigint NOT NULL DEFAULT 0, "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT 0, "timeToBeatCompletionist" bigint NOT NULL DEFAULT 0, "gameplayMain" double precision NOT NULL DEFAULT 0, "gameplayCompletionist" double precision NOT NULL DEFAULT 0, "imageUrl" character varying NOT NULL, CONSTRAINT "PK_c6fbf5fc15e97e46c2659dccea1" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `, undefined);
    await queryRunner.query(`CREATE TABLE "keyword" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "keyword" character varying NOT NULL, "response" character varying NOT NULL, "enabled" boolean NOT NULL, CONSTRAINT "PK_affdb8c8fa5b442900cb3aa21dc" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_35e3ff88225eef1d85c951e229" ON "keyword" ("keyword") `, undefined);
    await queryRunner.query(`CREATE TABLE "moderation_warning" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, CONSTRAINT "PK_0e90c9d7ff04a18218299cfc0e9" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_f941603aef2741795a9108d0d2" ON "moderation_warning" ("username") `, undefined);
    await queryRunner.query(`CREATE TABLE "moderation_permit" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, CONSTRAINT "PK_ba3b81de5de7feff025898b4a63" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_69499e78c9ee1602baee77b97d" ON "moderation_permit" ("username") `, undefined);
    await queryRunner.query(`CREATE TABLE "moderation_message_cooldown" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, CONSTRAINT "PK_f04b88fc0a7e570198d2016180d" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45ad701f0c2955bc09b5661898" ON "moderation_message_cooldown" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "order" integer NOT NULL, "isCorePermission" boolean NOT NULL, "isWaterfallAllowed" boolean NOT NULL, "automation" character varying(12) NOT NULL, "userIds" text NOT NULL, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "permission_filters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comparator" character varying(3) NOT NULL, "type" character varying NOT NULL, "value" bigint NOT NULL, "permissionId" uuid, CONSTRAINT "PK_e3e133ddb5ae7ccbc506864d696" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "permission_commands" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "permission" character varying(36), CONSTRAINT "PK_bfbb3cdf4fc0add3e790ba7ce59" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_ba6483f5c5882fa15299f22c0a" ON "permission_commands" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "poll" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(6) NOT NULL, "title" character varying NOT NULL, "isOpened" boolean NOT NULL, "openedAt" bigint NOT NULL DEFAULT 0, "closedAt" bigint NOT NULL DEFAULT 0, "options" text NOT NULL, CONSTRAINT "PK_03b5cf19a7f562b231c3458527e" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "poll_vote" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "option" integer NOT NULL, "votes" integer NOT NULL, "votedBy" character varying NOT NULL, "pollId" uuid, CONSTRAINT "PK_fd002d371201c472490ba89c6a0" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "price" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "command" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "price" integer NOT NULL, CONSTRAINT "PK_d163e55e8cce6908b2e0f27cea4" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d12db23d28020784096bcb41a3" ON "price" ("command") `, undefined);
    await queryRunner.query(`CREATE TABLE "queue" ("id" SERIAL NOT NULL, "createdAt" bigint NOT NULL, "username" character varying NOT NULL, "isModerator" boolean NOT NULL, "isSubscriber" boolean NOT NULL, "isFollower" boolean NOT NULL, CONSTRAINT "PK_4adefbd9c73b3f9a49985a5529f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7401b4e0c30f5de6621b38f7a0" ON "queue" ("username") `, undefined);
    await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tags" text NOT NULL, "quote" character varying NOT NULL, "quotedBy" integer NOT NULL, "createdAt" bigint NOT NULL, CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "raffle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "winner" text, "timestamp" bigint NOT NULL DEFAULT 0, "keyword" character varying NOT NULL, "minTickets" bigint NOT NULL DEFAULT 0, "maxTickets" bigint NOT NULL DEFAULT 0, "type" integer NOT NULL, "forFollowers" boolean NOT NULL, "forSubscribers" boolean NOT NULL, "isClosed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f9dee47f552e25482a1f65c282e" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_e83facaeb8fbe8b8ce9577209a" ON "raffle" ("keyword") `, undefined);
    await queryRunner.query(`CREATE TABLE "raffle_participant" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "tickets" integer NOT NULL, "isEligible" boolean NOT NULL, "isFollower" boolean NOT NULL, "isSubscriber" boolean NOT NULL, "raffleId" uuid, CONSTRAINT "PK_5d6f2b4fadbd927710cc2dd1e9f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "raffle_participant_message" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, "text" text NOT NULL, "participantId" integer, CONSTRAINT "PK_0355c24ac848612dc4232be2c0a" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "rank" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hours" integer NOT NULL, "rank" character varying NOT NULL, CONSTRAINT "PK_a5dfd2e605e5e4fb8578caec083" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_93c78c94804a13befdace81904" ON "rank" ("hours") `, undefined);
    await queryRunner.query(`CREATE TABLE "scrim_match_id" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "matchId" character varying NOT NULL, CONSTRAINT "PK_1cfb598145201e3f643598cbffe" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5af6da125c1745151e0dfaf087" ON "scrim_match_id" ("username") `, undefined);
    await queryRunner.query(`CREATE TABLE "settings" ("id" SERIAL NOT NULL, "namespace" character varying NOT NULL, "name" character varying NOT NULL, "value" text NOT NULL, CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_d8a83b9ffce680092c8dfee37d" ON "settings" ("namespace") `, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_ca7857276d2a30f4dcfa0e42cd" ON "settings" ("name") `, undefined);
    await queryRunner.query(`CREATE TABLE "song_playlist" ("videoId" character varying NOT NULL, "lastPlayedAt" bigint NOT NULL DEFAULT 0, "seed" double precision NOT NULL, "title" character varying NOT NULL, "loudness" double precision NOT NULL, "length" integer NOT NULL, "forceVolume" boolean NOT NULL DEFAULT false, "volume" integer NOT NULL, "startTime" integer NOT NULL, "endTime" integer NOT NULL, CONSTRAINT "PK_47041c19b2a8a264b51a592c9d0" PRIMARY KEY ("videoId"))`, undefined);
    await queryRunner.query(`CREATE TABLE "song_request" ("videoId" character varying NOT NULL, "addedAt" bigint NOT NULL DEFAULT 0, "title" character varying NOT NULL, "loudness" double precision NOT NULL, "length" integer NOT NULL, "username" character varying NOT NULL, CONSTRAINT "PK_54c0e42814d77cc6828ff6acf54" PRIMARY KEY ("videoId"))`, undefined);
    await queryRunner.query(`CREATE TABLE "song_ban" ("videoId" character varying NOT NULL, "title" character varying NOT NULL, CONSTRAINT "PK_387b2109574f60ff7797b9206e7" PRIMARY KEY ("videoId"))`, undefined);
    await queryRunner.query(`CREATE TABLE "text" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "text" text NOT NULL, "css" text NOT NULL, "js" text NOT NULL, "external" text NOT NULL, CONSTRAINT "PK_ef734161ea7c326fedf699309f9" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "thread_event" ("id" SERIAL NOT NULL, "event" character varying NOT NULL, CONSTRAINT "PK_03e2240b9bcaf166187eeb758fe" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_b8f5d0db148b37b4791a5e22c1" ON "thread_event" ("event") `, undefined);
    await queryRunner.query(`CREATE TABLE "timer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "isEnabled" boolean NOT NULL, "triggerEveryMessage" integer NOT NULL, "triggerEverySecond" integer NOT NULL, "triggeredAtTimestamp" bigint NOT NULL DEFAULT 0, "triggeredAtMessages" bigint NOT NULL DEFAULT 0, CONSTRAINT "PK_b476163e854c74bff55b29d320a" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "timer_response" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" bigint NOT NULL DEFAULT 0, "isEnabled" boolean NOT NULL DEFAULT true, "response" text NOT NULL, "timerId" uuid, CONSTRAINT "PK_785cbaf79acecb2971252bf609e" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "translation" ("value" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_a672a9127c15aa989a43e25074b" PRIMARY KEY ("name"))`, undefined);
    await queryRunner.query(`CREATE TABLE "twitch_tag" ("tag_id" character varying NOT NULL, "is_auto" boolean NOT NULL, "is_current" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_5437740946bb9a59053e3cfd4d0" PRIMARY KEY ("tag_id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "twitch_tag_localization_name" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "locale" character varying NOT NULL, "value" character varying NOT NULL, "tagId" character varying, CONSTRAINT "PK_bcb0baf06a5cf5d718e3d9bc7bd" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_dcf417a56c907f3a6788476047" ON "twitch_tag_localization_name" ("tagId") `, undefined);
    await queryRunner.query(`CREATE TABLE "twitch_tag_localization_description" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "locale" character varying NOT NULL, "value" character varying NOT NULL, "tagId" character varying, CONSTRAINT "PK_3d4eb98cbc6bb8d1deb1258ed7c" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_4d8108fc3e8dcbe5c112f53dd3" ON "twitch_tag_localization_description" ("tagId") `, undefined);
    await queryRunner.query(`CREATE TABLE "twitch_stats" ("whenOnline" bigint NOT NULL, "currentViewers" integer NOT NULL DEFAULT 0, "currentSubscribers" integer NOT NULL DEFAULT 0, "currentBits" bigint NOT NULL, "currentTips" float NOT NULL, "chatMessages" bigint NOT NULL, "currentFollowers" integer NOT NULL DEFAULT 0, "currentViews" integer NOT NULL DEFAULT 0, "maxViewers" integer NOT NULL DEFAULT 0, "currentHosts" integer NOT NULL DEFAULT 0, "newChatters" integer NOT NULL DEFAULT 0, "currentWatched" bigint NOT NULL, CONSTRAINT "PK_78b460c61f065e858da863e8102" PRIMARY KEY ("whenOnline"))`, undefined);
    await queryRunner.query(`CREATE TABLE "twitch_clips" ("clipId" character varying NOT NULL, "isChecked" boolean NOT NULL, "shouldBeCheckedAt" bigint NOT NULL, CONSTRAINT "PK_5692cf462da9f11803b3cf8f3dc" PRIMARY KEY ("clipId"))`, undefined);
    await queryRunner.query(`CREATE TABLE "user" ("userId" integer NOT NULL, "username" character varying NOT NULL, "displayname" character varying NOT NULL DEFAULT '', "profileImageUrl" character varying NOT NULL DEFAULT '', "isOnline" boolean NOT NULL DEFAULT false, "isVIP" boolean NOT NULL DEFAULT false, "isFollower" boolean NOT NULL DEFAULT false, "isModerator" boolean NOT NULL DEFAULT false, "isSubscriber" boolean NOT NULL DEFAULT false, "haveSubscriberLock" boolean NOT NULL DEFAULT false, "haveFollowerLock" boolean NOT NULL DEFAULT false, "haveSubscribedAtLock" boolean NOT NULL DEFAULT false, "haveFollowedAtLock" boolean NOT NULL DEFAULT false, "rank" character varying NOT NULL DEFAULT '', "haveCustomRank" boolean NOT NULL DEFAULT false, "followedAt" bigint NOT NULL DEFAULT 0, "followCheckAt" bigint NOT NULL DEFAULT 0, "subscribedAt" bigint NOT NULL DEFAULT 0, "seenAt" bigint NOT NULL DEFAULT 0, "createdAt" bigint NOT NULL DEFAULT 0, "watchedTime" bigint NOT NULL DEFAULT 0, "chatTimeOnline" bigint NOT NULL DEFAULT 0, "chatTimeOffline" bigint NOT NULL DEFAULT 0, "points" bigint NOT NULL DEFAULT 0, "pointsOnlineGivenAt" bigint NOT NULL DEFAULT 0, "pointsOfflineGivenAt" bigint NOT NULL DEFAULT 0, "pointsByMessageGivenAt" bigint NOT NULL DEFAULT 0, "subscribeTier" character varying NOT NULL DEFAULT '0', "subscribeCumulativeMonths" integer NOT NULL DEFAULT 0, "subscribeStreak" integer NOT NULL DEFAULT 0, "giftedSubscribes" bigint NOT NULL DEFAULT 0, "messages" bigint NOT NULL DEFAULT 0, CONSTRAINT "PK_d72ea127f30e21753c9e229891e" PRIMARY KEY ("userId"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `, undefined);
    await queryRunner.query(`CREATE TABLE "user_tip" ("id" SERIAL NOT NULL, "amount" double precision NOT NULL, "currency" character varying NOT NULL, "message" character varying NOT NULL DEFAULT '', "tippedAt" bigint NOT NULL DEFAULT 0, "sortAmount" double precision NOT NULL, "userUserId" integer, CONSTRAINT "PK_0bea18dcc7e730784d58261dffd" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "user_bit" ("id" SERIAL NOT NULL, "amount" bigint NOT NULL, "message" character varying NOT NULL DEFAULT '', "cheeredAt" bigint NOT NULL DEFAULT 0, "userUserId" integer, CONSTRAINT "PK_a944c6c776bab8b2e69126ed141" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "variable" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "variableName" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "type" character varying NOT NULL, "currentValue" character varying NOT NULL, "evalValue" text NOT NULL, "runEveryTypeValue" integer NOT NULL DEFAULT 60000, "runEveryType" character varying NOT NULL DEFAULT 'isUsed', "runEvery" integer NOT NULL DEFAULT 60000, "responseType" integer NOT NULL, "responseText" character varying NOT NULL DEFAULT '', "permission" character varying NOT NULL, "readOnly" boolean NOT NULL DEFAULT false, "usableOptions" text NOT NULL, "runAt" bigint NOT NULL DEFAULT 0, CONSTRAINT "PK_f4e200785984484787e6b47e6fb" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "variable_history" ("id" SERIAL NOT NULL, "userId" integer NOT NULL DEFAULT 0, "username" character varying NOT NULL DEFAULT 'n/a', "currentValue" character varying NOT NULL, "oldValue" text NOT NULL, "changedAt" bigint NOT NULL DEFAULT 0, "variableId" uuid, CONSTRAINT "PK_5285580f16e1286dd39fef7c7a4" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "variable_url" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "GET" boolean NOT NULL DEFAULT false, "POST" boolean NOT NULL DEFAULT false, "showResponse" boolean NOT NULL DEFAULT false, "variableId" uuid, CONSTRAINT "PK_20351f97b3c3f5e86656021d7fa" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "variable_watch" ("id" SERIAL NOT NULL, "variableId" character varying NOT NULL, "order" integer NOT NULL, CONSTRAINT "PK_fa090e3c43468f9b1793439cb5e" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "widget_social" ("id" character varying NOT NULL, "type" character varying NOT NULL, "hashtag" character varying NOT NULL, "text" text NOT NULL, "username" character varying NOT NULL, "displayname" character varying NOT NULL, "url" character varying NOT NULL, "timestamp" bigint NOT NULL DEFAULT 0, CONSTRAINT "PK_e57865605d678d69c5e4450f1fe" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_follow" ADD CONSTRAINT "FK_6e7a73361ade12e7e69040a7c07" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_sub" ADD CONSTRAINT "FK_52aaa81fff666f516b021774b60" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_subgift" ADD CONSTRAINT "FK_79f7ce25e52da9ab0085b237c52" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_host" ADD CONSTRAINT "FK_c665ba36c06d60912fdaf8bb9cc" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_raid" ADD CONSTRAINT "FK_aa40fffe0016d3700315f5b4c24" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_tip" ADD CONSTRAINT "FK_05e3dcbf185b77f33cc4078dba2" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_cheer" ADD CONSTRAINT "FK_09f1fb76339fc4afffc74b37db7" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_resub" ADD CONSTRAINT "FK_25ce77691f1aa94d954c0f88ecd" FOREIGN KEY ("alertId") REFERENCES "alert"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "bets_participations" ADD CONSTRAINT "FK_f4888a939a9c39297bd786c5e9c" FOREIGN KEY ("betId") REFERENCES "bets"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "commands_responses" ADD CONSTRAINT "FK_09da90fa3264f486de9be57b185" FOREIGN KEY ("commandId") REFERENCES "commands"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "cooldown_viewer" ADD CONSTRAINT "FK_5ba6ccf5a51426111e322c80445" FOREIGN KEY ("cooldownId") REFERENCES "cooldown"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "widget" ADD CONSTRAINT "FK_95877f9f08f5663fd6a177c5a0e" FOREIGN KEY ("dashboardId") REFERENCES "dashboard"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "event_operation" ADD CONSTRAINT "FK_a9f07bd7a9f0b7b9d41f48b476d" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "goal" ADD CONSTRAINT "FK_a1a6bd23cb8ef7ddf921f54c0bb" FOREIGN KEY ("groupId") REFERENCES "goal_group"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "permission_filters" ADD CONSTRAINT "FK_58a2c7864182d942bea393b4420" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "poll_vote" ADD CONSTRAINT "FK_99f9db6d3dae2a0aebebbf8e10a" FOREIGN KEY ("pollId") REFERENCES "poll"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "raffle_participant" ADD CONSTRAINT "FK_bc112542267bdd487f4479a94a1" FOREIGN KEY ("raffleId") REFERENCES "raffle"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5" FOREIGN KEY ("participantId") REFERENCES "raffle_participant"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "timer_response" ADD CONSTRAINT "FK_3192b176b66d4375368c9e960de" FOREIGN KEY ("timerId") REFERENCES "timer"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "twitch_tag_localization_name" ADD CONSTRAINT "FK_dcf417a56c907f3a6788476047b" FOREIGN KEY ("tagId") REFERENCES "twitch_tag"("tag_id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "twitch_tag_localization_description" ADD CONSTRAINT "FK_4d8108fc3e8dcbe5c112f53dd3f" FOREIGN KEY ("tagId") REFERENCES "twitch_tag"("tag_id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "user_tip" ADD CONSTRAINT "FK_36683fb221201263b38344a9880" FOREIGN KEY ("userUserId") REFERENCES "user"("userId") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "user_bit" ADD CONSTRAINT "FK_cca96526faa532e7d20a0f775b0" FOREIGN KEY ("userUserId") REFERENCES "user"("userId") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "variable_history" ADD CONSTRAINT "FK_94d39c77652e9c332751a0cee02" FOREIGN KEY ("variableId") REFERENCES "variable"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`ALTER TABLE "variable_url" ADD CONSTRAINT "FK_806e97dff1efce7f8872b6d4500" FOREIGN KEY ("variableId") REFERENCES "variable"("id") ON DELETE CASCADE ON UPDATE CASCADE`, undefined);
    await queryRunner.query(`CREATE TABLE "query-result-cache" ("id" SERIAL NOT NULL, "identifier" character varying, "time" bigint NOT NULL, "duration" integer NOT NULL, "query" text NOT NULL, "result" text NOT NULL, CONSTRAINT "PK_6a98f758d8bfd010e7e10ffd3d3" PRIMARY KEY ("id"))`, undefined);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`DROP TABLE "query-result-cache"`, undefined);
    await queryRunner.query(`ALTER TABLE "variable_url" DROP CONSTRAINT "FK_806e97dff1efce7f8872b6d4500"`, undefined);
    await queryRunner.query(`ALTER TABLE "variable_history" DROP CONSTRAINT "FK_94d39c77652e9c332751a0cee02"`, undefined);
    await queryRunner.query(`ALTER TABLE "user_bit" DROP CONSTRAINT "FK_cca96526faa532e7d20a0f775b0"`, undefined);
    await queryRunner.query(`ALTER TABLE "user_tip" DROP CONSTRAINT "FK_36683fb221201263b38344a9880"`, undefined);
    await queryRunner.query(`ALTER TABLE "twitch_tag_localization_description" DROP CONSTRAINT "FK_4d8108fc3e8dcbe5c112f53dd3f"`, undefined);
    await queryRunner.query(`ALTER TABLE "twitch_tag_localization_name" DROP CONSTRAINT "FK_dcf417a56c907f3a6788476047b"`, undefined);
    await queryRunner.query(`ALTER TABLE "timer_response" DROP CONSTRAINT "FK_3192b176b66d4375368c9e960de"`, undefined);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5"`, undefined);
    await queryRunner.query(`ALTER TABLE "raffle_participant" DROP CONSTRAINT "FK_bc112542267bdd487f4479a94a1"`, undefined);
    await queryRunner.query(`ALTER TABLE "poll_vote" DROP CONSTRAINT "FK_99f9db6d3dae2a0aebebbf8e10a"`, undefined);
    await queryRunner.query(`ALTER TABLE "permission_filters" DROP CONSTRAINT "FK_58a2c7864182d942bea393b4420"`, undefined);
    await queryRunner.query(`ALTER TABLE "goal" DROP CONSTRAINT "FK_a1a6bd23cb8ef7ddf921f54c0bb"`, undefined);
    await queryRunner.query(`ALTER TABLE "event_operation" DROP CONSTRAINT "FK_a9f07bd7a9f0b7b9d41f48b476d"`, undefined);
    await queryRunner.query(`ALTER TABLE "widget" DROP CONSTRAINT "FK_95877f9f08f5663fd6a177c5a0e"`, undefined);
    await queryRunner.query(`ALTER TABLE "cooldown_viewer" DROP CONSTRAINT "FK_5ba6ccf5a51426111e322c80445"`, undefined);
    await queryRunner.query(`ALTER TABLE "commands_responses" DROP CONSTRAINT "FK_09da90fa3264f486de9be57b185"`, undefined);
    await queryRunner.query(`ALTER TABLE "bets_participations" DROP CONSTRAINT "FK_f4888a939a9c39297bd786c5e9c"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_resub" DROP CONSTRAINT "FK_25ce77691f1aa94d954c0f88ecd"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_cheer" DROP CONSTRAINT "FK_09f1fb76339fc4afffc74b37db7"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_tip" DROP CONSTRAINT "FK_05e3dcbf185b77f33cc4078dba2"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_raid" DROP CONSTRAINT "FK_aa40fffe0016d3700315f5b4c24"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_host" DROP CONSTRAINT "FK_c665ba36c06d60912fdaf8bb9cc"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_subgift" DROP CONSTRAINT "FK_79f7ce25e52da9ab0085b237c52"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_sub" DROP CONSTRAINT "FK_52aaa81fff666f516b021774b60"`, undefined);
    await queryRunner.query(`ALTER TABLE "alert_follow" DROP CONSTRAINT "FK_6e7a73361ade12e7e69040a7c07"`, undefined);
    await queryRunner.query(`DROP TABLE "widget_social"`, undefined);
    await queryRunner.query(`DROP TABLE "variable_watch"`, undefined);
    await queryRunner.query(`DROP TABLE "variable_url"`, undefined);
    await queryRunner.query(`DROP TABLE "variable_history"`, undefined);
    await queryRunner.query(`DROP TABLE "variable"`, undefined);
    await queryRunner.query(`DROP TABLE "user_bit"`, undefined);
    await queryRunner.query(`DROP TABLE "user_tip"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_78a916df40e02a9deb1c4b75ed"`, undefined);
    await queryRunner.query(`DROP TABLE "user"`, undefined);
    await queryRunner.query(`DROP TABLE "twitch_clips"`, undefined);
    await queryRunner.query(`DROP TABLE "twitch_stats"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_4d8108fc3e8dcbe5c112f53dd3"`, undefined);
    await queryRunner.query(`DROP TABLE "twitch_tag_localization_description"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_dcf417a56c907f3a6788476047"`, undefined);
    await queryRunner.query(`DROP TABLE "twitch_tag_localization_name"`, undefined);
    await queryRunner.query(`DROP TABLE "twitch_tag"`, undefined);
    await queryRunner.query(`DROP TABLE "translation"`, undefined);
    await queryRunner.query(`DROP TABLE "timer_response"`, undefined);
    await queryRunner.query(`DROP TABLE "timer"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_b8f5d0db148b37b4791a5e22c1"`, undefined);
    await queryRunner.query(`DROP TABLE "thread_event"`, undefined);
    await queryRunner.query(`DROP TABLE "text"`, undefined);
    await queryRunner.query(`DROP TABLE "song_ban"`, undefined);
    await queryRunner.query(`DROP TABLE "song_request"`, undefined);
    await queryRunner.query(`DROP TABLE "song_playlist"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_ca7857276d2a30f4dcfa0e42cd"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_d8a83b9ffce680092c8dfee37d"`, undefined);
    await queryRunner.query(`DROP TABLE "settings"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_5af6da125c1745151e0dfaf087"`, undefined);
    await queryRunner.query(`DROP TABLE "scrim_match_id"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_93c78c94804a13befdace81904"`, undefined);
    await queryRunner.query(`DROP TABLE "rank"`, undefined);
    await queryRunner.query(`DROP TABLE "raffle_participant_message"`, undefined);
    await queryRunner.query(`DROP TABLE "raffle_participant"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_e83facaeb8fbe8b8ce9577209a"`, undefined);
    await queryRunner.query(`DROP TABLE "raffle"`, undefined);
    await queryRunner.query(`DROP TABLE "quotes"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_7401b4e0c30f5de6621b38f7a0"`, undefined);
    await queryRunner.query(`DROP TABLE "queue"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_d12db23d28020784096bcb41a3"`, undefined);
    await queryRunner.query(`DROP TABLE "price"`, undefined);
    await queryRunner.query(`DROP TABLE "poll_vote"`, undefined);
    await queryRunner.query(`DROP TABLE "poll"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_ba6483f5c5882fa15299f22c0a"`, undefined);
    await queryRunner.query(`DROP TABLE "permission_commands"`, undefined);
    await queryRunner.query(`DROP TABLE "permission_filters"`, undefined);
    await queryRunner.query(`DROP TABLE "permissions"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_45ad701f0c2955bc09b5661898"`, undefined);
    await queryRunner.query(`DROP TABLE "moderation_message_cooldown"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_69499e78c9ee1602baee77b97d"`, undefined);
    await queryRunner.query(`DROP TABLE "moderation_permit"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_f941603aef2741795a9108d0d2"`, undefined);
    await queryRunner.query(`DROP TABLE "moderation_warning"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_35e3ff88225eef1d85c951e229"`, undefined);
    await queryRunner.query(`DROP TABLE "keyword"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`, undefined);
    await queryRunner.query(`DROP TABLE "how_long_to_beat_game"`, undefined);
    await queryRunner.query(`DROP TABLE "highlight"`, undefined);
    await queryRunner.query(`DROP TABLE "heist_user"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_a1a6bd23cb8ef7ddf921f54c0b"`, undefined);
    await queryRunner.query(`DROP TABLE "goal"`, undefined);
    await queryRunner.query(`DROP TABLE "goal_group"`, undefined);
    await queryRunner.query(`DROP TABLE "gallery"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_8a80a3cf6b2d815920a390968a"`, undefined);
    await queryRunner.query(`DROP TABLE "event_list"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_daf6b97e1e5a5c779055fbb22d"`, undefined);
    await queryRunner.query(`DROP TABLE "event_operation"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_b535fbe8ec6d832dde22065ebd"`, undefined);
    await queryRunner.query(`DROP TABLE "event"`, undefined);
    await queryRunner.query(`DROP TABLE "duel"`, undefined);
    await queryRunner.query(`DROP TABLE "widget"`, undefined);
    await queryRunner.query(`DROP TABLE "dashboard"`, undefined);
    await queryRunner.query(`DROP TABLE "cooldown_viewer"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_aa85aa267ec6eaddf7f93e3665"`, undefined);
    await queryRunner.query(`DROP TABLE "cooldown"`, undefined);
    await queryRunner.query(`DROP TABLE "commands_board"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_2ccf816b1dd74e9a02845c4818"`, undefined);
    await queryRunner.query(`DROP TABLE "commands_count"`, undefined);
    await queryRunner.query(`DROP TABLE "commands_responses"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_1a8c40f0a581447776c325cb4f"`, undefined);
    await queryRunner.query(`DROP TABLE "commands"`, undefined);
    await queryRunner.query(`DROP TABLE "checklist"`, undefined);
    await queryRunner.query(`DROP TABLE "changelog"`, undefined);
    await queryRunner.query(`DROP TABLE "carousel"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_a0c6ce833b5b3b13325e6f49b0"`, undefined);
    await queryRunner.query(`DROP TABLE "cache_titles"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_f37be3c66dbd449a8cb4fe7d59"`, undefined);
    await queryRunner.query(`DROP TABLE "cache_games"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_36cd5732ccfc2693662be974f9"`, undefined);
    await queryRunner.query(`DROP TABLE "cache_emotes"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_eb26a8222f1ed29abbef861295"`, undefined);
    await queryRunner.query(`DROP TABLE "bets_participations"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_df40819eb0eb71d2cc7d73cea8"`, undefined);
    await queryRunner.query(`DROP TABLE "bets"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_ed5fcb69444dcb0abf0a71053b"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_6a8a594f0a5546f8082b0c405c"`, undefined);
    await queryRunner.query(`DROP TABLE "alias"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_resub"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_cheer"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_tip"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_raid"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_host"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_subgift"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_sub"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_follow"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_b0f12c32653ed88fd576d3520c"`, undefined);
    await queryRunner.query(`DROP TABLE "alert_media"`, undefined);
    await queryRunner.query(`DROP TABLE "alert"`, undefined);
  }

}
