import { MigrationInterface, QueryRunner } from 'typeorm';

export class alertsRewardRedeem1604241327525 implements MigrationInterface {
  name = 'alertsRewardRedeem1604241327525';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "alert_reward_redeem" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOut" varchar NOT NULL, "animationOutDuration" integer NOT NULL DEFAULT (2000), "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "message" text NOT NULL, "rewardId" varchar NOT NULL)`);
    await queryRunner.query(`CREATE TABLE "temporary_alert_reward_redeem" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOut" varchar NOT NULL, "animationOutDuration" integer NOT NULL DEFAULT (2000), "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "message" text NOT NULL, "rewardId" varchar NOT NULL, CONSTRAINT "FK_c55befc36aa21345e5f27513eb3" FOREIGN KEY ("alertId") REFERENCES "alert" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "temporary_alert_reward_redeem"("id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationInDuration", "animationOut", "animationOutDuration", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "message", "rewardId") SELECT "id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationInDuration", "animationOut", "animationOutDuration", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "message", "rewardId" FROM "alert_reward_redeem"`);
    await queryRunner.query(`DROP TABLE "alert_reward_redeem"`);
    await queryRunner.query(`ALTER TABLE "temporary_alert_reward_redeem" RENAME TO "alert_reward_redeem"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "alert_reward_redeem" RENAME TO "temporary_alert_reward_redeem"`);
    await queryRunner.query(`CREATE TABLE "alert_reward_redeem" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOut" varchar NOT NULL, "animationOutDuration" integer NOT NULL DEFAULT (2000), "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "message" text NOT NULL, "rewardId" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "alert_reward_redeem"("id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationInDuration", "animationOut", "animationOutDuration", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "message", "rewardId") SELECT "id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationInDuration", "animationOut", "animationOutDuration", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "message", "rewardId" FROM "temporary_alert_reward_redeem"`);
    await queryRunner.query(`DROP TABLE "temporary_alert_reward_redeem"`);
    await queryRunner.query(`DROP TABLE "alert_reward_redeem"`);
  }

}
