import { MigrationInterface, QueryRunner } from 'typeorm';

export class alertsHostRemoveAutohost1609951363191 implements MigrationInterface {
  name = 'alertsHostRemoveAutohost1609951363191';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "temporary_alert_host" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationOut" varchar NOT NULL, "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOutDuration" integer NOT NULL DEFAULT (2000), "imageOptions" text NOT NULL, CONSTRAINT "FK_c665ba36c06d60912fdaf8bb9cc" FOREIGN KEY ("alertId") REFERENCES "alert" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "temporary_alert_host"("id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions") SELECT "id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions" FROM "alert_host"`);
    await queryRunner.query(`DROP TABLE "alert_host"`);
    await queryRunner.query(`ALTER TABLE "temporary_alert_host" RENAME TO "alert_host"`);
    await queryRunner.query(`CREATE TABLE "temporary_alert_raid" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationOut" varchar NOT NULL, "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOutDuration" integer NOT NULL DEFAULT (2000), "imageOptions" text NOT NULL, CONSTRAINT "FK_aa40fffe0016d3700315f5b4c24" FOREIGN KEY ("alertId") REFERENCES "alert" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "temporary_alert_raid"("id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions") SELECT "id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions" FROM "alert_raid"`);
    await queryRunner.query(`DROP TABLE "alert_raid"`);
    await queryRunner.query(`ALTER TABLE "temporary_alert_raid" RENAME TO "alert_raid"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "alert_raid" RENAME TO "temporary_alert_raid"`);
    await queryRunner.query(`CREATE TABLE "alert_raid" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationOut" varchar NOT NULL, "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "showAutoHost" boolean NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOutDuration" integer NOT NULL DEFAULT (2000), "imageOptions" text NOT NULL, CONSTRAINT "FK_aa40fffe0016d3700315f5b4c24" FOREIGN KEY ("alertId") REFERENCES "alert" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "alert_raid"("id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions") SELECT "id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions" FROM "temporary_alert_raid"`);
    await queryRunner.query(`DROP TABLE "temporary_alert_raid"`);
    await queryRunner.query(`ALTER TABLE "alert_host" RENAME TO "temporary_alert_host"`);
    await queryRunner.query(`CREATE TABLE "alert_host" ("id" varchar PRIMARY KEY NOT NULL, "alertId" varchar, "enabled" boolean NOT NULL, "title" varchar NOT NULL, "variantCondition" varchar NOT NULL, "variantAmount" integer NOT NULL, "messageTemplate" varchar NOT NULL, "layout" varchar NOT NULL, "animationIn" varchar NOT NULL, "animationOut" varchar NOT NULL, "animationText" varchar NOT NULL, "animationTextOptions" text NOT NULL, "imageId" varchar NOT NULL, "soundId" varchar NOT NULL, "soundVolume" integer NOT NULL, "alertDurationInMs" integer NOT NULL, "alertTextDelayInMs" integer NOT NULL, "enableAdvancedMode" boolean NOT NULL, "advancedMode" text NOT NULL, "tts" text NOT NULL, "font" text NOT NULL, "showAutoHost" boolean NOT NULL, "animationInDuration" integer NOT NULL DEFAULT (2000), "animationOutDuration" integer NOT NULL DEFAULT (2000), "imageOptions" text NOT NULL, CONSTRAINT "FK_c665ba36c06d60912fdaf8bb9cc" FOREIGN KEY ("alertId") REFERENCES "alert" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "alert_host"("id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions") SELECT "id", "alertId", "enabled", "title", "variantCondition", "variantAmount", "messageTemplate", "layout", "animationIn", "animationOut", "animationText", "animationTextOptions", "imageId", "soundId", "soundVolume", "alertDurationInMs", "alertTextDelayInMs", "enableAdvancedMode", "advancedMode", "tts", "font", "animationInDuration", "animationOutDuration", "imageOptions" FROM "temporary_alert_host"`);
    await queryRunner.query(`DROP TABLE "temporary_alert_host"`);
  }

}
