import { MigrationInterface, QueryRunner } from 'typeorm';

export class initialize1000000000001 implements MigrationInterface {
  transaction?: boolean | undefined;
  name = 'initialize1000000000001';

  public async up(queryRunner: QueryRunner): Promise<any> {
    const migrations = await queryRunner.query(`SELECT * FROM \`migrations\``);
    if (migrations.length > 0) {
      console.log('Skipping migration zero, migrations are already in bot');
      return;
    }
    await queryRunner.query(`CREATE TABLE \`alert\` (\`id\` varchar(36) NOT NULL, \`updatedAt\` varchar(30) NULL, \`name\` varchar(255) NOT NULL, \`alertDelayInMs\` int NOT NULL, \`profanityFilterType\` varchar(255) NOT NULL, \`loadStandardProfanityList\` json NOT NULL, \`parry\` json NOT NULL, \`tts\` json NULL, \`fontMessage\` json NOT NULL, \`font\` json NOT NULL, \`customProfanityList\` varchar(255) NOT NULL, \`items\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`alias\` (\`id\` varchar(36) NOT NULL, \`alias\` varchar(255) NOT NULL, \`command\` text NOT NULL, \`enabled\` tinyint NOT NULL, \`visible\` tinyint NOT NULL, \`permission\` varchar(255) NULL, \`group\` varchar(255) NULL, INDEX \`IDX_6a8a594f0a5546f8082b0c405c\` (\`alias\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`alias_group\` (\`name\` varchar(255) NOT NULL, \`options\` text NOT NULL, UNIQUE INDEX \`IDX_alias_group_unique_name\` (\`name\`), PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`bets\` (\`id\` varchar(36) NOT NULL, \`createdAt\` varchar(30) NOT NULL, \`endedAt\` varchar(30) NOT NULL, \`isLocked\` tinyint NOT NULL DEFAULT 0, \`arePointsGiven\` tinyint NOT NULL DEFAULT 0, \`options\` text NOT NULL, \`title\` varchar(255) NOT NULL, \`participants\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`commands\` (\`id\` varchar(36) NOT NULL, \`command\` varchar(255) NOT NULL, \`enabled\` tinyint NOT NULL, \`visible\` tinyint NOT NULL, \`group\` varchar(255) NULL, \`areResponsesRandomized\` tinyint NOT NULL DEFAULT 0, \`responses\` json NOT NULL, INDEX \`IDX_1a8c40f0a581447776c325cb4f\` (\`command\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`commands_group\` (\`name\` varchar(255) NOT NULL, \`options\` text NOT NULL, UNIQUE INDEX \`IDX_commands_group_unique_name\` (\`name\`), PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`commands_count\` (\`id\` varchar(36) NOT NULL, \`command\` varchar(255) NOT NULL, \`timestamp\` varchar(30) NOT NULL, INDEX \`IDX_2ccf816b1dd74e9a02845c4818\` (\`command\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`cooldown\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`miliseconds\` int NOT NULL, \`type\` varchar(10) NOT NULL, \`timestamp\` varchar(30) NOT NULL, \`isEnabled\` tinyint NOT NULL, \`isErrorMsgQuiet\` tinyint NOT NULL, \`isOwnerAffected\` tinyint NOT NULL, \`isModeratorAffected\` tinyint NOT NULL, \`isSubscriberAffected\` tinyint NOT NULL, UNIQUE INDEX \`IDX_aa85aa267ec6eaddf7f93e3665\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`highlight\` (\`id\` varchar(36) NOT NULL, \`videoId\` varchar(255) NOT NULL, \`game\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`expired\` tinyint NOT NULL DEFAULT 0, \`timestamp\` json NOT NULL, \`createdAt\` varchar(30) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`how_long_to_beat_game\` (\`id\` varchar(36) NOT NULL, \`game\` varchar(255) NOT NULL, \`startedAt\` varchar(30) NOT NULL, \`updatedAt\` varchar(30) NOT NULL, \`gameplayMain\` float(12) NOT NULL DEFAULT '0', \`gameplayMainExtra\` float(12) NOT NULL DEFAULT '0', \`gameplayCompletionist\` float(12) NOT NULL DEFAULT '0', \`offset\` bigint NOT NULL DEFAULT '0', \`streams\` json NOT NULL, UNIQUE INDEX \`IDX_301758e0e3108fc902d5436527\` (\`game\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`keyword\` (\`id\` varchar(36) NOT NULL, \`keyword\` varchar(255) NOT NULL, \`enabled\` tinyint NOT NULL, \`group\` varchar(255) NULL, INDEX \`IDX_35e3ff88225eef1d85c951e229\` (\`keyword\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`keyword_responses\` (\`id\` varchar(36) NOT NULL, \`order\` int NOT NULL, \`response\` text NOT NULL, \`stopIfExecuted\` tinyint NOT NULL, \`permission\` varchar(255) NULL, \`filter\` varchar(255) NOT NULL, \`keywordId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`keyword_group\` (\`name\` varchar(255) NOT NULL, \`options\` text NOT NULL, UNIQUE INDEX \`IDX_keyword_group_unique_name\` (\`name\`), PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`obswebsocket\` (\`id\` varchar(14) NOT NULL, \`name\` varchar(255) NOT NULL, \`code\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`overlay\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`canvas\` json NOT NULL, \`items\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`order\` int NOT NULL, \`isCorePermission\` tinyint NOT NULL, \`isWaterfallAllowed\` tinyint NOT NULL, \`automation\` varchar(12) NOT NULL, \`userIds\` text NOT NULL, \`excludeUserIds\` text NOT NULL, \`filters\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`permission_commands\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`permission\` varchar(36) NULL, INDEX \`IDX_ba6483f5c5882fa15299f22c0a\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`namespace\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`value\` longtext NOT NULL, UNIQUE INDEX \`IDX_d8a83b9ffce680092c8dfee37d\` (\`namespace\`, \`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`plugin\` (\`id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`enabled\` tinyint NOT NULL, \`workflow\` longtext NOT NULL, \`settings\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`plugin_variable\` (\`variableName\` varchar(255) NOT NULL, \`pluginId\` varchar(255) NOT NULL, \`value\` longtext NOT NULL, PRIMARY KEY (\`variableName\`, \`pluginId\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`poll\` (\`id\` varchar(36) NOT NULL, \`type\` varchar(7) NOT NULL, \`title\` varchar(255) NOT NULL, \`openedAt\` varchar(30) NOT NULL, \`closedAt\` varchar(30) NULL, \`options\` text NOT NULL, \`votes\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`price\` (\`id\` varchar(36) NOT NULL, \`command\` varchar(255) NOT NULL, \`enabled\` tinyint NOT NULL DEFAULT 1, \`emitRedeemEvent\` tinyint NOT NULL DEFAULT 0, \`price\` int NOT NULL, \`priceBits\` int NOT NULL DEFAULT '0', UNIQUE INDEX \`IDX_d12db23d28020784096bcb41a3\` (\`command\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`quotes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`tags\` text NOT NULL, \`quote\` varchar(255) NOT NULL, \`quotedBy\` varchar(255) NOT NULL, \`createdAt\` varchar(30) NOT NULL DEFAULT '1970-01-01T00:00:00.000Z', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`randomizer\` (\`id\` varchar(36) NOT NULL, \`items\` json NOT NULL, \`createdAt\` varchar(30) NOT NULL, \`command\` varchar(255) NOT NULL, \`permissionId\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`isShown\` tinyint NOT NULL DEFAULT 0, \`shouldPlayTick\` tinyint NOT NULL, \`tickVolume\` int NOT NULL, \`widgetOrder\` int NOT NULL, \`type\` varchar(20) NOT NULL DEFAULT 'simple', \`position\` json NOT NULL, \`customizationFont\` json NOT NULL, \`tts\` json NOT NULL, UNIQUE INDEX \`idx_randomizer_cmdunique\` (\`command\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`rank\` (\`id\` varchar(36) NOT NULL, \`value\` int NOT NULL, \`rank\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_93c78c94804a13befdace81904\` (\`type\`, \`value\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`song_ban\` (\`videoId\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, PRIMARY KEY (\`videoId\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`song_playlist\` (\`videoId\` varchar(255) NOT NULL, \`lastPlayedAt\` varchar(30) NOT NULL DEFAULT '1970-01-01T00:00:00.000Z', \`title\` varchar(255) NOT NULL, \`seed\` float(12) NOT NULL, \`loudness\` float(12) NOT NULL, \`tags\` text NOT NULL, \`length\` int NOT NULL, \`volume\` int NOT NULL, \`startTime\` int NOT NULL, \`endTime\` int NOT NULL, \`forceVolume\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`videoId\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`song_request\` (\`id\` varchar(36) NOT NULL, \`videoId\` varchar(255) NOT NULL, \`addedAt\` varchar(30) NOT NULL, \`title\` varchar(255) NOT NULL, \`loudness\` float(12) NOT NULL, \`length\` int NOT NULL, \`username\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`spotify_song_ban\` (\`spotifyUri\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`artists\` text NOT NULL, PRIMARY KEY (\`spotifyUri\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`timer\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`isEnabled\` tinyint NOT NULL, \`tickOffline\` tinyint NOT NULL DEFAULT 0, \`triggerEveryMessage\` int NOT NULL, \`triggerEverySecond\` int NOT NULL, \`triggeredAtTimestamp\` varchar(30) NOT NULL DEFAULT '1970-01-01T00:00:00.000Z', \`triggeredAtMessages\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`timer_response\` (\`id\` varchar(36) NOT NULL, \`timestamp\` varchar(30) NOT NULL DEFAULT '1970-01-01T00:00:00.000Z', \`isEnabled\` tinyint NOT NULL DEFAULT 1, \`response\` text NOT NULL, \`timerId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`variable_watch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`variableId\` varchar(255) NOT NULL, \`order\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`variable\` (\`id\` varchar(36) NOT NULL, \`history\` json NOT NULL, \`urls\` json NOT NULL, \`variableName\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL DEFAULT '', \`type\` varchar(255) NOT NULL, \`currentValue\` varchar(255) NULL, \`evalValue\` text NOT NULL, \`runEvery\` int NOT NULL DEFAULT '60000', \`responseType\` int NOT NULL, \`responseText\` varchar(255) NOT NULL DEFAULT '', \`permission\` varchar(255) NOT NULL, \`readOnly\` tinyint NOT NULL DEFAULT 0, \`usableOptions\` text NOT NULL, \`runAt\` varchar(30) NOT NULL, UNIQUE INDEX \`IDX_dd084634ad76dbefdca837b8de\` (\`variableName\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`cache_games\` (\`id\` int NOT NULL, \`name\` varchar(255) NOT NULL, \`thumbnail\` varchar(255) NULL, INDEX \`IDX_f37be3c66dbd449a8cb4fe7d59\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`cache_titles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`game\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`tags\` text NOT NULL, \`timestamp\` bigint NOT NULL, INDEX \`IDX_a0c6ce833b5b3b13325e6f49b0\` (\`game\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`carousel\` (\`id\` varchar(36) NOT NULL, \`order\` int NOT NULL, \`type\` varchar(255) NOT NULL, \`waitAfter\` int NOT NULL, \`waitBefore\` int NOT NULL, \`duration\` int NOT NULL, \`animationIn\` varchar(255) NOT NULL, \`animationInDuration\` int NOT NULL, \`animationOut\` varchar(255) NOT NULL, \`animationOutDuration\` int NOT NULL, \`showOnlyOncePerStream\` tinyint NOT NULL, \`base64\` longtext NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`checklist\` (\`id\` varchar(255) NOT NULL, \`isCompleted\` tinyint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`quickaction\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`order\` int NOT NULL, \`type\` varchar(255) NOT NULL, \`options\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`discord_link\` (\`id\` varchar(36) NOT NULL, \`tag\` varchar(255) NOT NULL, \`discordId\` varchar(255) NOT NULL, \`createdAt\` bigint NOT NULL, \`userId\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`duel\` (\`id\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`tickets\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`event\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`isEnabled\` tinyint NOT NULL, \`triggered\` text NOT NULL, \`definitions\` text NOT NULL, \`filter\` varchar(255) NOT NULL, INDEX \`IDX_b535fbe8ec6d832dde22065ebd\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`event_operation\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`definitions\` text NOT NULL, \`eventId\` varchar(36) NULL, INDEX \`IDX_daf6b97e1e5a5c779055fbb22d\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`event_list\` (\`id\` varchar(36) NOT NULL, \`event\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`timestamp\` bigint NOT NULL, \`isTest\` tinyint NOT NULL, \`isHidden\` tinyint NOT NULL DEFAULT 0, \`values_json\` text NOT NULL, INDEX \`IDX_8a80a3cf6b2d815920a390968a\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`gallery\` (\`id\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`data\` longtext NOT NULL, \`name\` varchar(255) NOT NULL, \`folder\` varchar(255) NOT NULL DEFAULT '/', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`goal_group\` (\`id\` varchar(36) NOT NULL, \`createdAt\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`display\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`goal\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`groupId\` varchar(255) NULL, \`type\` varchar(20) NOT NULL, \`countBitsAsTips\` tinyint NOT NULL, \`display\` varchar(20) NOT NULL, \`timestamp\` varchar(255) NULL, \`interval\` varchar(255) NOT NULL DEFAULT 'hour', \`tiltifyCampaign\` int NULL, \`goalAmount\` float(12) NOT NULL DEFAULT '0', \`currentAmount\` float(12) NOT NULL DEFAULT '0', \`endAfter\` varchar(255) NOT NULL, \`endAfterIgnore\` tinyint NOT NULL, \`customizationBar\` text NOT NULL, \`customizationFont\` text NOT NULL, \`customizationHtml\` text NOT NULL, \`customizationJs\` text NOT NULL, \`customizationCss\` text NOT NULL, INDEX \`IDX_a1a6bd23cb8ef7ddf921f54c0b\` (\`groupId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`google_private_keys\` (\`id\` varchar(36) NOT NULL, \`clientEmail\` varchar(255) NOT NULL, \`privateKey\` longtext NOT NULL, \`createdAt\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`heist_user\` (\`userId\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`points\` bigint NOT NULL, PRIMARY KEY (\`userId\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`moderation_warning\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`timestamp\` bigint NOT NULL DEFAULT '0', INDEX \`IDX_f941603aef2741795a9108d0d2\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`moderation_permit\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, INDEX \`IDX_69499e78c9ee1602baee77b97d\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`points_changelog\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL, \`originalValue\` int NOT NULL, \`updatedValue\` int NOT NULL, \`updatedAt\` bigint NOT NULL, \`command\` varchar(255) NOT NULL, INDEX \`IDX_points_changelog_userId\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`queue\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` bigint NOT NULL, \`username\` varchar(255) NOT NULL, \`isModerator\` tinyint NOT NULL, \`isSubscriber\` tinyint NOT NULL, \`message\` varchar(255) NULL, UNIQUE INDEX \`IDX_7401b4e0c30f5de6621b38f7a0\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`raffle\` (\`id\` varchar(36) NOT NULL, \`winner\` text NULL, \`timestamp\` bigint NOT NULL DEFAULT '0', \`keyword\` varchar(255) NOT NULL, \`minTickets\` bigint NOT NULL DEFAULT '0', \`maxTickets\` bigint NOT NULL DEFAULT '0', \`type\` int NOT NULL, \`forSubscribers\` tinyint NOT NULL, \`isClosed\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_e83facaeb8fbe8b8ce9577209a\` (\`keyword\`), INDEX \`IDX_raffleIsClosed\` (\`isClosed\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`raffle_participant\` (\`id\` varchar(36) NOT NULL, \`username\` varchar(255) NOT NULL, \`tickets\` int NOT NULL, \`isEligible\` tinyint NOT NULL, \`isSubscriber\` tinyint NOT NULL, \`raffleId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`raffle_participant_message\` (\`id\` varchar(36) NOT NULL, \`timestamp\` bigint NOT NULL DEFAULT '0', \`text\` text NOT NULL, \`participantId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`scrim_match_id\` (\`id\` varchar(36) NOT NULL, \`username\` varchar(255) NOT NULL, \`matchId\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_5af6da125c1745151e0dfaf087\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`text\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`text\` text NOT NULL, \`css\` text NOT NULL, \`js\` text NOT NULL, \`external\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`translation\` (\`name\` varchar(255) NOT NULL, \`value\` varchar(255) NOT NULL, PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`twitch_stats\` (\`whenOnline\` bigint NOT NULL, \`currentViewers\` int NOT NULL DEFAULT '0', \`currentSubscribers\` int NOT NULL DEFAULT '0', \`chatMessages\` bigint NOT NULL, \`currentFollowers\` int NOT NULL DEFAULT '0', \`maxViewers\` int NOT NULL DEFAULT '0', \`newChatters\` int NOT NULL DEFAULT '0', \`currentBits\` bigint NOT NULL, \`currentTips\` float(12) NOT NULL, \`currentWatched\` bigint NOT NULL, PRIMARY KEY (\`whenOnline\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`twitch_clips\` (\`clipId\` varchar(255) NOT NULL, \`isChecked\` tinyint NOT NULL, \`shouldBeCheckedAt\` bigint NOT NULL, PRIMARY KEY (\`clipId\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`user\` (\`userId\` varchar(255) NOT NULL, \`userName\` varchar(255) NOT NULL, \`displayname\` varchar(255) NOT NULL DEFAULT '', \`profileImageUrl\` varchar(255) NOT NULL DEFAULT '', \`isOnline\` tinyint NOT NULL DEFAULT 0, \`isVIP\` tinyint NOT NULL DEFAULT 0, \`isModerator\` tinyint NOT NULL DEFAULT 0, \`isSubscriber\` tinyint NOT NULL DEFAULT 0, \`haveSubscriberLock\` tinyint NOT NULL DEFAULT 0, \`haveSubscribedAtLock\` tinyint NOT NULL DEFAULT 0, \`rank\` varchar(255) NOT NULL DEFAULT '', \`haveCustomRank\` tinyint NOT NULL DEFAULT 0, \`subscribedAt\` varchar(30) NULL, \`seenAt\` varchar(30) NULL, \`createdAt\` varchar(30) NULL, \`watchedTime\` bigint NOT NULL DEFAULT '0', \`chatTimeOnline\` bigint NOT NULL DEFAULT '0', \`chatTimeOffline\` bigint NOT NULL DEFAULT '0', \`points\` bigint NOT NULL DEFAULT '0', \`pointsOnlineGivenAt\` bigint NOT NULL DEFAULT '0', \`pointsOfflineGivenAt\` bigint NOT NULL DEFAULT '0', \`pointsByMessageGivenAt\` bigint NOT NULL DEFAULT '0', \`subscribeTier\` varchar(255) NOT NULL DEFAULT '0', \`subscribeCumulativeMonths\` int NOT NULL DEFAULT '0', \`subscribeStreak\` int NOT NULL DEFAULT '0', \`giftedSubscribes\` bigint NOT NULL DEFAULT '0', \`messages\` bigint NOT NULL DEFAULT '0', \`extra\` text NULL, INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` (\`userName\`), PRIMARY KEY (\`userId\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`user_tip\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` float(12) NOT NULL, \`sortAmount\` float(12) NOT NULL, \`exchangeRates\` text NOT NULL, \`currency\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`tippedAt\` bigint NOT NULL DEFAULT '0', \`userId\` varchar(255) NULL, INDEX \`IDX_user_tip_userId\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`user_bit\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` bigint NOT NULL, \`message\` text NOT NULL, \`cheeredAt\` bigint NOT NULL DEFAULT '0', \`userId\` varchar(255) NULL, INDEX \`IDX_user_bit_userId\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`widget_custom\` (\`id\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`widget_social\` (\`id\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`hashtag\` varchar(255) NOT NULL, \`text\` text NOT NULL, \`username\` varchar(255) NOT NULL, \`displayname\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`timestamp\` bigint NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`ALTER TABLE \`keyword_responses\` ADD CONSTRAINT \`FK_d12716a3805d58dd75ab09c8c67\` FOREIGN KEY (\`keywordId\`) REFERENCES \`keyword\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE \`timer_response\` ADD CONSTRAINT \`FK_3192b176b66d4375368c9e960de\` FOREIGN KEY (\`timerId\`) REFERENCES \`timer\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE \`event_operation\` ADD CONSTRAINT \`FK_a9f07bd7a9f0b7b9d41f48b476d\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE \`goal\` ADD CONSTRAINT \`FK_a1a6bd23cb8ef7ddf921f54c0bb\` FOREIGN KEY (\`groupId\`) REFERENCES \`goal_group\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE \`raffle_participant\` ADD CONSTRAINT \`FK_bc112542267bdd487f4479a94a1\` FOREIGN KEY (\`raffleId\`) REFERENCES \`raffle\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE \`raffle_participant_message\` ADD CONSTRAINT \`FK_e6eda53bcd6ceb62b5edd9e02b5\` FOREIGN KEY (\`participantId\`) REFERENCES \`raffle_participant\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    return;
  }

}