import { MigrationInterface, QueryRunner } from 'typeorm';

export class idAlign1602499070261 implements MigrationInterface {
  name = 'idAlign1602499070261';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "checklist" DROP CONSTRAINT "PK_e4b437f5107f2a9d5b744d4eb4c"`);
    await queryRunner.query(`ALTER TABLE "checklist" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "checklist" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "checklist" ADD CONSTRAINT "PK_e4b437f5107f2a9d5b744d4eb4c" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "commands_count" DROP CONSTRAINT "PK_80e221b846abb1a84ab81281a7a"`);
    await queryRunner.query(`ALTER TABLE "commands_count" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "commands_count" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "commands_count" ADD CONSTRAINT "PK_80e221b846abb1a84ab81281a7a" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "event_list" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "event_list" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "event_list" ADD CONSTRAINT "PK_1cc2e9353e9ae8acf95d976cf6f" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "highlight" DROP CONSTRAINT "PK_0f4191998a1e1e8f8455f1d4adb"`);
    await queryRunner.query(`ALTER TABLE "highlight" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "highlight" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "highlight" ADD CONSTRAINT "PK_0f4191998a1e1e8f8455f1d4adb" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" DROP CONSTRAINT "PK_c6fbf5fc15e97e46c2659dccea1"`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" ADD CONSTRAINT "PK_c6fbf5fc15e97e46c2659dccea1" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" DROP CONSTRAINT "PK_0e90c9d7ff04a18218299cfc0e9"`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" ADD CONSTRAINT "PK_0e90c9d7ff04a18218299cfc0e9" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" DROP CONSTRAINT "PK_ba3b81de5de7feff025898b4a63"`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" ADD CONSTRAINT "PK_ba3b81de5de7feff025898b4a63" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" DROP CONSTRAINT "PK_f04b88fc0a7e570198d2016180d"`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" ADD CONSTRAINT "PK_f04b88fc0a7e570198d2016180d" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "permission_commands" DROP CONSTRAINT "PK_bfbb3cdf4fc0add3e790ba7ce59"`);
    await queryRunner.query(`ALTER TABLE "permission_commands" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "permission_commands" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "permission_commands" ADD CONSTRAINT "PK_bfbb3cdf4fc0add3e790ba7ce59" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" DROP CONSTRAINT "PK_5d6f2b4fadbd927710cc2dd1e9f"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" ADD CONSTRAINT "PK_5d6f2b4fadbd927710cc2dd1e9f" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP CONSTRAINT "PK_0355c24ac848612dc4232be2c0a"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD CONSTRAINT "PK_0355c24ac848612dc4232be2c0a" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP COLUMN "participantId"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD "participantId" uuid`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" DROP CONSTRAINT "PK_1cfb598145201e3f643598cbffe"`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" ADD CONSTRAINT "PK_1cfb598145201e3f643598cbffe" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "thread_event" DROP CONSTRAINT "PK_03e2240b9bcaf166187eeb758fe"`);
    await queryRunner.query(`ALTER TABLE "thread_event" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "thread_event" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
    await queryRunner.query(`ALTER TABLE "thread_event" ADD CONSTRAINT "PK_03e2240b9bcaf166187eeb758fe" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5" FOREIGN KEY ("participantId") REFERENCES "raffle_participant"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5"`);
    await queryRunner.query(`ALTER TABLE "thread_event" DROP CONSTRAINT "PK_03e2240b9bcaf166187eeb758fe"`);
    await queryRunner.query(`ALTER TABLE "thread_event" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "thread_event" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "thread_event" ADD CONSTRAINT "PK_03e2240b9bcaf166187eeb758fe" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" DROP CONSTRAINT "PK_1cfb598145201e3f643598cbffe"`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" ADD CONSTRAINT "PK_1cfb598145201e3f643598cbffe" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP COLUMN "participantId"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD "participantId" integer`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP CONSTRAINT "PK_0355c24ac848612dc4232be2c0a"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD CONSTRAINT "PK_0355c24ac848612dc4232be2c0a" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" DROP CONSTRAINT "PK_5d6f2b4fadbd927710cc2dd1e9f"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" ADD CONSTRAINT "PK_5d6f2b4fadbd927710cc2dd1e9f" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" ADD CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5" FOREIGN KEY ("participantId") REFERENCES "raffle_participant"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE "permission_commands" DROP CONSTRAINT "PK_bfbb3cdf4fc0add3e790ba7ce59"`);
    await queryRunner.query(`ALTER TABLE "permission_commands" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "permission_commands" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "permission_commands" ADD CONSTRAINT "PK_bfbb3cdf4fc0add3e790ba7ce59" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" DROP CONSTRAINT "PK_f04b88fc0a7e570198d2016180d"`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" ADD CONSTRAINT "PK_f04b88fc0a7e570198d2016180d" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" DROP CONSTRAINT "PK_ba3b81de5de7feff025898b4a63"`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" ADD CONSTRAINT "PK_ba3b81de5de7feff025898b4a63" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" DROP CONSTRAINT "PK_0e90c9d7ff04a18218299cfc0e9"`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" ADD CONSTRAINT "PK_0e90c9d7ff04a18218299cfc0e9" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" DROP CONSTRAINT "PK_c6fbf5fc15e97e46c2659dccea1"`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" ADD CONSTRAINT "PK_c6fbf5fc15e97e46c2659dccea1" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "highlight" DROP CONSTRAINT "PK_0f4191998a1e1e8f8455f1d4adb"`);
    await queryRunner.query(`ALTER TABLE "highlight" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "highlight" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "highlight" ADD CONSTRAINT "PK_0f4191998a1e1e8f8455f1d4adb" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "event_list" DROP CONSTRAINT "PK_1cc2e9353e9ae8acf95d976cf6f"`);
    await queryRunner.query(`ALTER TABLE "event_list" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "event_list" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "event_list" ADD CONSTRAINT "PK_1cc2e9353e9ae8acf95d976cf6f" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "commands_count" DROP CONSTRAINT "PK_80e221b846abb1a84ab81281a7a"`);
    await queryRunner.query(`ALTER TABLE "commands_count" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "commands_count" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "commands_count" ADD CONSTRAINT "PK_80e221b846abb1a84ab81281a7a" PRIMARY KEY ("id")`);
    await queryRunner.query(`ALTER TABLE "checklist" DROP CONSTRAINT "PK_e4b437f5107f2a9d5b744d4eb4c"`);
    await queryRunner.query(`ALTER TABLE "checklist" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "checklist" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(`ALTER TABLE "checklist" ADD CONSTRAINT "PK_e4b437f5107f2a9d5b744d4eb4c" PRIMARY KEY ("id")`);
  }

}