import { MigrationInterface, QueryRunner } from 'typeorm';

export class idAlign1602499070261 implements MigrationInterface {
  name = 'idAlign1602499070261';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "temporary_checklist" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "isCompleted" boolean NOT NULL, "value" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_checklist"("id", "isCompleted", "value") SELECT "id", "isCompleted", "value" FROM "checklist"`);
    await queryRunner.query(`DROP TABLE "checklist"`);
    await queryRunner.query(`ALTER TABLE "temporary_checklist" RENAME TO "checklist"`);
    await queryRunner.query(`DROP INDEX "IDX_2ccf816b1dd74e9a02845c4818"`);
    await queryRunner.query(`CREATE TABLE "temporary_commands_count" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "command" varchar NOT NULL, "timestamp" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_commands_count"("id", "command", "timestamp") SELECT "id", "command", "timestamp" FROM "commands_count"`);
    await queryRunner.query(`DROP TABLE "commands_count"`);
    await queryRunner.query(`ALTER TABLE "temporary_commands_count" RENAME TO "commands_count"`);
    await queryRunner.query(`CREATE INDEX "IDX_2ccf816b1dd74e9a02845c4818" ON "commands_count" ("command") `);
    await queryRunner.query(`DROP INDEX "IDX_8a80a3cf6b2d815920a390968a"`);
    await queryRunner.query(`CREATE TABLE "temporary_event_list" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "event" varchar NOT NULL, "userId" varchar NOT NULL, "timestamp" bigint NOT NULL, "values_json" text NOT NULL, "isTest" boolean NOT NULL, "isHidden" boolean NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "temporary_event_list"("id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden") SELECT "id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden" FROM "event_list"`);
    await queryRunner.query(`DROP TABLE "event_list"`);
    await queryRunner.query(`ALTER TABLE "temporary_event_list" RENAME TO "event_list"`);
    await queryRunner.query(`CREATE INDEX "IDX_8a80a3cf6b2d815920a390968a" ON "event_list" ("userId") `);
    await queryRunner.query(`CREATE TABLE "temporary_highlight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "videoId" varchar NOT NULL, "game" varchar NOT NULL, "title" varchar NOT NULL, "timestamp" text NOT NULL, "createdAt" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_highlight"("id", "videoId", "game", "title", "timestamp", "createdAt") SELECT "id", "videoId", "game", "title", "timestamp", "createdAt" FROM "highlight"`);
    await queryRunner.query(`DROP TABLE "highlight"`);
    await queryRunner.query(`ALTER TABLE "temporary_highlight" RENAME TO "highlight"`);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`);
    await queryRunner.query(`CREATE TABLE "temporary_how_long_to_beat_game" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "game" varchar NOT NULL, "startedAt" bigint NOT NULL DEFAULT (0), "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT (0), "timeToBeatCompletionist" bigint NOT NULL DEFAULT (0), "gameplayMain" float NOT NULL DEFAULT (0), "gameplayCompletionist" float NOT NULL DEFAULT (0), "imageUrl" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_how_long_to_beat_game"("id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl") SELECT "id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl" FROM "how_long_to_beat_game"`);
    await queryRunner.query(`DROP TABLE "how_long_to_beat_game"`);
    await queryRunner.query(`ALTER TABLE "temporary_how_long_to_beat_game" RENAME TO "how_long_to_beat_game"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `);
    await queryRunner.query(`DROP INDEX "IDX_f941603aef2741795a9108d0d2"`);
    await queryRunner.query(`CREATE TABLE "temporary_moderation_warning" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "temporary_moderation_warning"("id", "userId", "timestamp") SELECT "id", "userId", "timestamp" FROM "moderation_warning"`);
    await queryRunner.query(`DROP TABLE "moderation_warning"`);
    await queryRunner.query(`ALTER TABLE "temporary_moderation_warning" RENAME TO "moderation_warning"`);
    await queryRunner.query(`CREATE INDEX "IDX_f941603aef2741795a9108d0d2" ON "moderation_warning" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_69499e78c9ee1602baee77b97d"`);
    await queryRunner.query(`CREATE TABLE "temporary_moderation_permit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_moderation_permit"("id", "userId") SELECT "id", "userId" FROM "moderation_permit"`);
    await queryRunner.query(`DROP TABLE "moderation_permit"`);
    await queryRunner.query(`ALTER TABLE "temporary_moderation_permit" RENAME TO "moderation_permit"`);
    await queryRunner.query(`CREATE INDEX "IDX_69499e78c9ee1602baee77b97d" ON "moderation_permit" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_45ad701f0c2955bc09b5661898"`);
    await queryRunner.query(`CREATE TABLE "temporary_moderation_message_cooldown" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "temporary_moderation_message_cooldown"("id", "name", "timestamp") SELECT "id", "name", "timestamp" FROM "moderation_message_cooldown"`);
    await queryRunner.query(`DROP TABLE "moderation_message_cooldown"`);
    await queryRunner.query(`ALTER TABLE "temporary_moderation_message_cooldown" RENAME TO "moderation_message_cooldown"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45ad701f0c2955bc09b5661898" ON "moderation_message_cooldown" ("name") `);
    await queryRunner.query(`DROP INDEX "IDX_ba6483f5c5882fa15299f22c0a"`);
    await queryRunner.query(`CREATE TABLE "temporary_permission_commands" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "permission" varchar(36))`);
    await queryRunner.query(`INSERT INTO "temporary_permission_commands"("id", "name", "permission") SELECT "id", "name", "permission" FROM "permission_commands"`);
    await queryRunner.query(`DROP TABLE "permission_commands"`);
    await queryRunner.query(`ALTER TABLE "temporary_permission_commands" RENAME TO "permission_commands"`);
    await queryRunner.query(`CREATE INDEX "IDX_ba6483f5c5882fa15299f22c0a" ON "permission_commands" ("name") `);
    await queryRunner.query(`CREATE TABLE "temporary_raffle_participant" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "tickets" integer NOT NULL, "isEligible" boolean NOT NULL, "isFollower" boolean NOT NULL, "isSubscriber" boolean NOT NULL, "raffleId" varchar, CONSTRAINT "FK_bc112542267bdd487f4479a94a1" FOREIGN KEY ("raffleId") REFERENCES "raffle" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "temporary_raffle_participant"("id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId") SELECT "id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId" FROM "raffle_participant"`);
    await queryRunner.query(`DROP TABLE "raffle_participant"`);
    await queryRunner.query(`ALTER TABLE "temporary_raffle_participant" RENAME TO "raffle_participant"`);
    await queryRunner.query(`DROP INDEX "IDX_5af6da125c1745151e0dfaf087"`);
    await queryRunner.query(`CREATE TABLE "temporary_scrim_match_id" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "matchId" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_scrim_match_id"("id", "username", "matchId") SELECT "id", "username", "matchId" FROM "scrim_match_id"`);
    await queryRunner.query(`DROP TABLE "scrim_match_id"`);
    await queryRunner.query(`ALTER TABLE "temporary_scrim_match_id" RENAME TO "scrim_match_id"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5af6da125c1745151e0dfaf087" ON "scrim_match_id" ("username") `);
    await queryRunner.query(`DROP INDEX "IDX_b8f5d0db148b37b4791a5e22c1"`);
    await queryRunner.query(`CREATE TABLE "temporary_thread_event" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "event" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_thread_event"("id", "event") SELECT "id", "event" FROM "thread_event"`);
    await queryRunner.query(`DROP TABLE "thread_event"`);
    await queryRunner.query(`ALTER TABLE "temporary_thread_event" RENAME TO "thread_event"`);
    await queryRunner.query(`CREATE INDEX "IDX_b8f5d0db148b37b4791a5e22c1" ON "thread_event" ("event") `);
    await queryRunner.query(`CREATE TABLE "temporary_checklist" ("id" varchar PRIMARY KEY NOT NULL, "isCompleted" boolean NOT NULL, "value" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_checklist"("id", "isCompleted", "value") SELECT "id", "isCompleted", "value" FROM "checklist"`);
    await queryRunner.query(`DROP TABLE "checklist"`);
    await queryRunner.query(`ALTER TABLE "temporary_checklist" RENAME TO "checklist"`);
    await queryRunner.query(`DROP INDEX "IDX_2ccf816b1dd74e9a02845c4818"`);
    await queryRunner.query(`CREATE TABLE "temporary_commands_count" ("id" varchar PRIMARY KEY NOT NULL, "command" varchar NOT NULL, "timestamp" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_commands_count"("id", "command", "timestamp") SELECT "id", "command", "timestamp" FROM "commands_count"`);
    await queryRunner.query(`DROP TABLE "commands_count"`);
    await queryRunner.query(`ALTER TABLE "temporary_commands_count" RENAME TO "commands_count"`);
    await queryRunner.query(`CREATE INDEX "IDX_2ccf816b1dd74e9a02845c4818" ON "commands_count" ("command") `);
    await queryRunner.query(`DROP INDEX "IDX_8a80a3cf6b2d815920a390968a"`);
    await queryRunner.query(`CREATE TABLE "temporary_event_list" ("id" varchar PRIMARY KEY NOT NULL, "event" varchar NOT NULL, "userId" varchar NOT NULL, "timestamp" bigint NOT NULL, "values_json" text NOT NULL, "isTest" boolean NOT NULL, "isHidden" boolean NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "temporary_event_list"("id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden") SELECT "id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden" FROM "event_list"`);
    await queryRunner.query(`DROP TABLE "event_list"`);
    await queryRunner.query(`ALTER TABLE "temporary_event_list" RENAME TO "event_list"`);
    await queryRunner.query(`CREATE INDEX "IDX_8a80a3cf6b2d815920a390968a" ON "event_list" ("userId") `);
    await queryRunner.query(`CREATE TABLE "temporary_highlight" ("id" varchar PRIMARY KEY NOT NULL, "videoId" varchar NOT NULL, "game" varchar NOT NULL, "title" varchar NOT NULL, "timestamp" text NOT NULL, "createdAt" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_highlight"("id", "videoId", "game", "title", "timestamp", "createdAt") SELECT "id", "videoId", "game", "title", "timestamp", "createdAt" FROM "highlight"`);
    await queryRunner.query(`DROP TABLE "highlight"`);
    await queryRunner.query(`ALTER TABLE "temporary_highlight" RENAME TO "highlight"`);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`);
    await queryRunner.query(`CREATE TABLE "temporary_how_long_to_beat_game" ("id" varchar PRIMARY KEY NOT NULL, "game" varchar NOT NULL, "startedAt" bigint NOT NULL DEFAULT (0), "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT (0), "timeToBeatCompletionist" bigint NOT NULL DEFAULT (0), "gameplayMain" float NOT NULL DEFAULT (0), "gameplayCompletionist" float NOT NULL DEFAULT (0), "imageUrl" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_how_long_to_beat_game"("id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl") SELECT "id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl" FROM "how_long_to_beat_game"`);
    await queryRunner.query(`DROP TABLE "how_long_to_beat_game"`);
    await queryRunner.query(`ALTER TABLE "temporary_how_long_to_beat_game" RENAME TO "how_long_to_beat_game"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `);
    await queryRunner.query(`DROP INDEX "IDX_f941603aef2741795a9108d0d2"`);
    await queryRunner.query(`CREATE TABLE "temporary_moderation_warning" ("id" varchar PRIMARY KEY NOT NULL, "userId" integer NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "temporary_moderation_warning"("id", "userId", "timestamp") SELECT "id", "userId", "timestamp" FROM "moderation_warning"`);
    await queryRunner.query(`DROP TABLE "moderation_warning"`);
    await queryRunner.query(`ALTER TABLE "temporary_moderation_warning" RENAME TO "moderation_warning"`);
    await queryRunner.query(`CREATE INDEX "IDX_f941603aef2741795a9108d0d2" ON "moderation_warning" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_69499e78c9ee1602baee77b97d"`);
    await queryRunner.query(`CREATE TABLE "temporary_moderation_permit" ("id" varchar PRIMARY KEY NOT NULL, "userId" integer NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_moderation_permit"("id", "userId") SELECT "id", "userId" FROM "moderation_permit"`);
    await queryRunner.query(`DROP TABLE "moderation_permit"`);
    await queryRunner.query(`ALTER TABLE "temporary_moderation_permit" RENAME TO "moderation_permit"`);
    await queryRunner.query(`CREATE INDEX "IDX_69499e78c9ee1602baee77b97d" ON "moderation_permit" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_45ad701f0c2955bc09b5661898"`);
    await queryRunner.query(`CREATE TABLE "temporary_moderation_message_cooldown" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "temporary_moderation_message_cooldown"("id", "name", "timestamp") SELECT "id", "name", "timestamp" FROM "moderation_message_cooldown"`);
    await queryRunner.query(`DROP TABLE "moderation_message_cooldown"`);
    await queryRunner.query(`ALTER TABLE "temporary_moderation_message_cooldown" RENAME TO "moderation_message_cooldown"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45ad701f0c2955bc09b5661898" ON "moderation_message_cooldown" ("name") `);
    await queryRunner.query(`DROP INDEX "IDX_ba6483f5c5882fa15299f22c0a"`);
    await queryRunner.query(`CREATE TABLE "temporary_permission_commands" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "permission" varchar(36))`);
    await queryRunner.query(`INSERT INTO "temporary_permission_commands"("id", "name", "permission") SELECT "id", "name", "permission" FROM "permission_commands"`);
    await queryRunner.query(`DROP TABLE "permission_commands"`);
    await queryRunner.query(`ALTER TABLE "temporary_permission_commands" RENAME TO "permission_commands"`);
    await queryRunner.query(`CREATE INDEX "IDX_ba6483f5c5882fa15299f22c0a" ON "permission_commands" ("name") `);
    await queryRunner.query(`CREATE TABLE "temporary_raffle_participant_message" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "text" text NOT NULL, "participantId" integer)`);
    await queryRunner.query(`INSERT INTO "temporary_raffle_participant_message"("id", "timestamp", "text", "participantId") SELECT "id", "timestamp", "text", "participantId" FROM "raffle_participant_message"`);
    await queryRunner.query(`DROP TABLE "raffle_participant_message"`);
    await queryRunner.query(`ALTER TABLE "temporary_raffle_participant_message" RENAME TO "raffle_participant_message"`);
    await queryRunner.query(`CREATE TABLE "temporary_raffle_participant" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "tickets" integer NOT NULL, "isEligible" boolean NOT NULL, "isFollower" boolean NOT NULL, "isSubscriber" boolean NOT NULL, "raffleId" varchar, CONSTRAINT "FK_bc112542267bdd487f4479a94a1" FOREIGN KEY ("raffleId") REFERENCES "raffle" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "temporary_raffle_participant"("id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId") SELECT "id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId" FROM "raffle_participant"`);
    await queryRunner.query(`DROP TABLE "raffle_participant"`);
    await queryRunner.query(`ALTER TABLE "temporary_raffle_participant" RENAME TO "raffle_participant"`);
    await queryRunner.query(`CREATE TABLE "temporary_raffle_participant_message" ("id" varchar PRIMARY KEY NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "text" text NOT NULL, "participantId" varchar)`);
    await queryRunner.query(`INSERT INTO "temporary_raffle_participant_message"("id", "timestamp", "text", "participantId") SELECT "id", "timestamp", "text", "participantId" FROM "raffle_participant_message"`);
    await queryRunner.query(`DROP TABLE "raffle_participant_message"`);
    await queryRunner.query(`ALTER TABLE "temporary_raffle_participant_message" RENAME TO "raffle_participant_message"`);
    await queryRunner.query(`DROP INDEX "IDX_5af6da125c1745151e0dfaf087"`);
    await queryRunner.query(`CREATE TABLE "temporary_scrim_match_id" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "matchId" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_scrim_match_id"("id", "username", "matchId") SELECT "id", "username", "matchId" FROM "scrim_match_id"`);
    await queryRunner.query(`DROP TABLE "scrim_match_id"`);
    await queryRunner.query(`ALTER TABLE "temporary_scrim_match_id" RENAME TO "scrim_match_id"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5af6da125c1745151e0dfaf087" ON "scrim_match_id" ("username") `);
    await queryRunner.query(`DROP INDEX "IDX_b8f5d0db148b37b4791a5e22c1"`);
    await queryRunner.query(`CREATE TABLE "temporary_thread_event" ("id" varchar PRIMARY KEY NOT NULL, "event" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "temporary_thread_event"("id", "event") SELECT "id", "event" FROM "thread_event"`);
    await queryRunner.query(`DROP TABLE "thread_event"`);
    await queryRunner.query(`ALTER TABLE "temporary_thread_event" RENAME TO "thread_event"`);
    await queryRunner.query(`CREATE INDEX "IDX_b8f5d0db148b37b4791a5e22c1" ON "thread_event" ("event") `);
    await queryRunner.query(`CREATE TABLE "temporary_raffle_participant_message" ("id" varchar PRIMARY KEY NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "text" text NOT NULL, "participantId" varchar, CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5" FOREIGN KEY ("participantId") REFERENCES "raffle_participant" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "temporary_raffle_participant_message"("id", "timestamp", "text", "participantId") SELECT "id", "timestamp", "text", "participantId" FROM "raffle_participant_message"`);
    await queryRunner.query(`DROP TABLE "raffle_participant_message"`);
    await queryRunner.query(`ALTER TABLE "temporary_raffle_participant_message" RENAME TO "raffle_participant_message"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" RENAME TO "temporary_raffle_participant_message"`);
    await queryRunner.query(`CREATE TABLE "raffle_participant_message" ("id" varchar PRIMARY KEY NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "text" text NOT NULL, "participantId" varchar)`);
    await queryRunner.query(`INSERT INTO "raffle_participant_message"("id", "timestamp", "text", "participantId") SELECT "id", "timestamp", "text", "participantId" FROM "temporary_raffle_participant_message"`);
    await queryRunner.query(`DROP TABLE "temporary_raffle_participant_message"`);
    await queryRunner.query(`DROP INDEX "IDX_b8f5d0db148b37b4791a5e22c1"`);
    await queryRunner.query(`ALTER TABLE "thread_event" RENAME TO "temporary_thread_event"`);
    await queryRunner.query(`CREATE TABLE "thread_event" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "event" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "thread_event"("id", "event") SELECT "id", "event" FROM "temporary_thread_event"`);
    await queryRunner.query(`DROP TABLE "temporary_thread_event"`);
    await queryRunner.query(`CREATE INDEX "IDX_b8f5d0db148b37b4791a5e22c1" ON "thread_event" ("event") `);
    await queryRunner.query(`DROP INDEX "IDX_5af6da125c1745151e0dfaf087"`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" RENAME TO "temporary_scrim_match_id"`);
    await queryRunner.query(`CREATE TABLE "scrim_match_id" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "matchId" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "scrim_match_id"("id", "username", "matchId") SELECT "id", "username", "matchId" FROM "temporary_scrim_match_id"`);
    await queryRunner.query(`DROP TABLE "temporary_scrim_match_id"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5af6da125c1745151e0dfaf087" ON "scrim_match_id" ("username") `);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" RENAME TO "temporary_raffle_participant_message"`);
    await queryRunner.query(`CREATE TABLE "raffle_participant_message" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "text" text NOT NULL, "participantId" integer)`);
    await queryRunner.query(`INSERT INTO "raffle_participant_message"("id", "timestamp", "text", "participantId") SELECT "id", "timestamp", "text", "participantId" FROM "temporary_raffle_participant_message"`);
    await queryRunner.query(`DROP TABLE "temporary_raffle_participant_message"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant" RENAME TO "temporary_raffle_participant"`);
    await queryRunner.query(`CREATE TABLE "raffle_participant" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "tickets" integer NOT NULL, "isEligible" boolean NOT NULL, "isFollower" boolean NOT NULL, "isSubscriber" boolean NOT NULL, "raffleId" varchar, CONSTRAINT "FK_bc112542267bdd487f4479a94a1" FOREIGN KEY ("raffleId") REFERENCES "raffle" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "raffle_participant"("id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId") SELECT "id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId" FROM "temporary_raffle_participant"`);
    await queryRunner.query(`DROP TABLE "temporary_raffle_participant"`);
    await queryRunner.query(`ALTER TABLE "raffle_participant_message" RENAME TO "temporary_raffle_participant_message"`);
    await queryRunner.query(`CREATE TABLE "raffle_participant_message" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "text" text NOT NULL, "participantId" integer, CONSTRAINT "FK_e6eda53bcd6ceb62b5edd9e02b5" FOREIGN KEY ("participantId") REFERENCES "raffle_participant" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "raffle_participant_message"("id", "timestamp", "text", "participantId") SELECT "id", "timestamp", "text", "participantId" FROM "temporary_raffle_participant_message"`);
    await queryRunner.query(`DROP TABLE "temporary_raffle_participant_message"`);
    await queryRunner.query(`DROP INDEX "IDX_ba6483f5c5882fa15299f22c0a"`);
    await queryRunner.query(`ALTER TABLE "permission_commands" RENAME TO "temporary_permission_commands"`);
    await queryRunner.query(`CREATE TABLE "permission_commands" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "permission" varchar(36))`);
    await queryRunner.query(`INSERT INTO "permission_commands"("id", "name", "permission") SELECT "id", "name", "permission" FROM "temporary_permission_commands"`);
    await queryRunner.query(`DROP TABLE "temporary_permission_commands"`);
    await queryRunner.query(`CREATE INDEX "IDX_ba6483f5c5882fa15299f22c0a" ON "permission_commands" ("name") `);
    await queryRunner.query(`DROP INDEX "IDX_45ad701f0c2955bc09b5661898"`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" RENAME TO "temporary_moderation_message_cooldown"`);
    await queryRunner.query(`CREATE TABLE "moderation_message_cooldown" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "moderation_message_cooldown"("id", "name", "timestamp") SELECT "id", "name", "timestamp" FROM "temporary_moderation_message_cooldown"`);
    await queryRunner.query(`DROP TABLE "temporary_moderation_message_cooldown"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45ad701f0c2955bc09b5661898" ON "moderation_message_cooldown" ("name") `);
    await queryRunner.query(`DROP INDEX "IDX_69499e78c9ee1602baee77b97d"`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" RENAME TO "temporary_moderation_permit"`);
    await queryRunner.query(`CREATE TABLE "moderation_permit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer NOT NULL)`);
    await queryRunner.query(`INSERT INTO "moderation_permit"("id", "userId") SELECT "id", "userId" FROM "temporary_moderation_permit"`);
    await queryRunner.query(`DROP TABLE "temporary_moderation_permit"`);
    await queryRunner.query(`CREATE INDEX "IDX_69499e78c9ee1602baee77b97d" ON "moderation_permit" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_f941603aef2741795a9108d0d2"`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" RENAME TO "temporary_moderation_warning"`);
    await queryRunner.query(`CREATE TABLE "moderation_warning" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "moderation_warning"("id", "userId", "timestamp") SELECT "id", "userId", "timestamp" FROM "temporary_moderation_warning"`);
    await queryRunner.query(`DROP TABLE "temporary_moderation_warning"`);
    await queryRunner.query(`CREATE INDEX "IDX_f941603aef2741795a9108d0d2" ON "moderation_warning" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" RENAME TO "temporary_how_long_to_beat_game"`);
    await queryRunner.query(`CREATE TABLE "how_long_to_beat_game" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "game" varchar NOT NULL, "startedAt" bigint NOT NULL DEFAULT (0), "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT (0), "timeToBeatCompletionist" bigint NOT NULL DEFAULT (0), "gameplayMain" float NOT NULL DEFAULT (0), "gameplayCompletionist" float NOT NULL DEFAULT (0), "imageUrl" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "how_long_to_beat_game"("id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl") SELECT "id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl" FROM "temporary_how_long_to_beat_game"`);
    await queryRunner.query(`DROP TABLE "temporary_how_long_to_beat_game"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `);
    await queryRunner.query(`ALTER TABLE "highlight" RENAME TO "temporary_highlight"`);
    await queryRunner.query(`CREATE TABLE "highlight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "videoId" varchar NOT NULL, "game" varchar NOT NULL, "title" varchar NOT NULL, "timestamp" text NOT NULL, "createdAt" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "highlight"("id", "videoId", "game", "title", "timestamp", "createdAt") SELECT "id", "videoId", "game", "title", "timestamp", "createdAt" FROM "temporary_highlight"`);
    await queryRunner.query(`DROP TABLE "temporary_highlight"`);
    await queryRunner.query(`DROP INDEX "IDX_8a80a3cf6b2d815920a390968a"`);
    await queryRunner.query(`ALTER TABLE "event_list" RENAME TO "temporary_event_list"`);
    await queryRunner.query(`CREATE TABLE "event_list" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "event" varchar NOT NULL, "userId" varchar NOT NULL, "timestamp" bigint NOT NULL, "values_json" text NOT NULL, "isTest" boolean NOT NULL, "isHidden" boolean NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "event_list"("id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden") SELECT "id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden" FROM "temporary_event_list"`);
    await queryRunner.query(`DROP TABLE "temporary_event_list"`);
    await queryRunner.query(`CREATE INDEX "IDX_8a80a3cf6b2d815920a390968a" ON "event_list" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_2ccf816b1dd74e9a02845c4818"`);
    await queryRunner.query(`ALTER TABLE "commands_count" RENAME TO "temporary_commands_count"`);
    await queryRunner.query(`CREATE TABLE "commands_count" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "command" varchar NOT NULL, "timestamp" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "commands_count"("id", "command", "timestamp") SELECT "id", "command", "timestamp" FROM "temporary_commands_count"`);
    await queryRunner.query(`DROP TABLE "temporary_commands_count"`);
    await queryRunner.query(`CREATE INDEX "IDX_2ccf816b1dd74e9a02845c4818" ON "commands_count" ("command") `);
    await queryRunner.query(`ALTER TABLE "checklist" RENAME TO "temporary_checklist"`);
    await queryRunner.query(`CREATE TABLE "checklist" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "isCompleted" boolean NOT NULL, "value" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "checklist"("id", "isCompleted", "value") SELECT "id", "isCompleted", "value" FROM "temporary_checklist"`);
    await queryRunner.query(`DROP TABLE "temporary_checklist"`);
    await queryRunner.query(`DROP INDEX "IDX_b8f5d0db148b37b4791a5e22c1"`);
    await queryRunner.query(`ALTER TABLE "thread_event" RENAME TO "temporary_thread_event"`);
    await queryRunner.query(`CREATE TABLE "thread_event" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "event" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "thread_event"("id", "event") SELECT "id", "event" FROM "temporary_thread_event"`);
    await queryRunner.query(`DROP TABLE "temporary_thread_event"`);
    await queryRunner.query(`CREATE INDEX "IDX_b8f5d0db148b37b4791a5e22c1" ON "thread_event" ("event") `);
    await queryRunner.query(`DROP INDEX "IDX_5af6da125c1745151e0dfaf087"`);
    await queryRunner.query(`ALTER TABLE "scrim_match_id" RENAME TO "temporary_scrim_match_id"`);
    await queryRunner.query(`CREATE TABLE "scrim_match_id" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "matchId" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "scrim_match_id"("id", "username", "matchId") SELECT "id", "username", "matchId" FROM "temporary_scrim_match_id"`);
    await queryRunner.query(`DROP TABLE "temporary_scrim_match_id"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5af6da125c1745151e0dfaf087" ON "scrim_match_id" ("username") `);
    await queryRunner.query(`ALTER TABLE "raffle_participant" RENAME TO "temporary_raffle_participant"`);
    await queryRunner.query(`CREATE TABLE "raffle_participant" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "tickets" integer NOT NULL, "isEligible" boolean NOT NULL, "isFollower" boolean NOT NULL, "isSubscriber" boolean NOT NULL, "raffleId" varchar, CONSTRAINT "FK_bc112542267bdd487f4479a94a1" FOREIGN KEY ("raffleId") REFERENCES "raffle" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
    await queryRunner.query(`INSERT INTO "raffle_participant"("id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId") SELECT "id", "username", "tickets", "isEligible", "isFollower", "isSubscriber", "raffleId" FROM "temporary_raffle_participant"`);
    await queryRunner.query(`DROP TABLE "temporary_raffle_participant"`);
    await queryRunner.query(`DROP INDEX "IDX_ba6483f5c5882fa15299f22c0a"`);
    await queryRunner.query(`ALTER TABLE "permission_commands" RENAME TO "temporary_permission_commands"`);
    await queryRunner.query(`CREATE TABLE "permission_commands" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "permission" varchar(36))`);
    await queryRunner.query(`INSERT INTO "permission_commands"("id", "name", "permission") SELECT "id", "name", "permission" FROM "temporary_permission_commands"`);
    await queryRunner.query(`DROP TABLE "temporary_permission_commands"`);
    await queryRunner.query(`CREATE INDEX "IDX_ba6483f5c5882fa15299f22c0a" ON "permission_commands" ("name") `);
    await queryRunner.query(`DROP INDEX "IDX_45ad701f0c2955bc09b5661898"`);
    await queryRunner.query(`ALTER TABLE "moderation_message_cooldown" RENAME TO "temporary_moderation_message_cooldown"`);
    await queryRunner.query(`CREATE TABLE "moderation_message_cooldown" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "moderation_message_cooldown"("id", "name", "timestamp") SELECT "id", "name", "timestamp" FROM "temporary_moderation_message_cooldown"`);
    await queryRunner.query(`DROP TABLE "temporary_moderation_message_cooldown"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45ad701f0c2955bc09b5661898" ON "moderation_message_cooldown" ("name") `);
    await queryRunner.query(`DROP INDEX "IDX_69499e78c9ee1602baee77b97d"`);
    await queryRunner.query(`ALTER TABLE "moderation_permit" RENAME TO "temporary_moderation_permit"`);
    await queryRunner.query(`CREATE TABLE "moderation_permit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer NOT NULL)`);
    await queryRunner.query(`INSERT INTO "moderation_permit"("id", "userId") SELECT "id", "userId" FROM "temporary_moderation_permit"`);
    await queryRunner.query(`DROP TABLE "temporary_moderation_permit"`);
    await queryRunner.query(`CREATE INDEX "IDX_69499e78c9ee1602baee77b97d" ON "moderation_permit" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_f941603aef2741795a9108d0d2"`);
    await queryRunner.query(`ALTER TABLE "moderation_warning" RENAME TO "temporary_moderation_warning"`);
    await queryRunner.query(`CREATE TABLE "moderation_warning" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "moderation_warning"("id", "userId", "timestamp") SELECT "id", "userId", "timestamp" FROM "temporary_moderation_warning"`);
    await queryRunner.query(`DROP TABLE "temporary_moderation_warning"`);
    await queryRunner.query(`CREATE INDEX "IDX_f941603aef2741795a9108d0d2" ON "moderation_warning" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" RENAME TO "temporary_how_long_to_beat_game"`);
    await queryRunner.query(`CREATE TABLE "how_long_to_beat_game" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "game" varchar NOT NULL, "startedAt" bigint NOT NULL DEFAULT (0), "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT (0), "timeToBeatCompletionist" bigint NOT NULL DEFAULT (0), "gameplayMain" float NOT NULL DEFAULT (0), "gameplayCompletionist" float NOT NULL DEFAULT (0), "imageUrl" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "how_long_to_beat_game"("id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl") SELECT "id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl" FROM "temporary_how_long_to_beat_game"`);
    await queryRunner.query(`DROP TABLE "temporary_how_long_to_beat_game"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `);
    await queryRunner.query(`ALTER TABLE "highlight" RENAME TO "temporary_highlight"`);
    await queryRunner.query(`CREATE TABLE "highlight" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "videoId" varchar NOT NULL, "game" varchar NOT NULL, "title" varchar NOT NULL, "timestamp" text NOT NULL, "createdAt" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "highlight"("id", "videoId", "game", "title", "timestamp", "createdAt") SELECT "id", "videoId", "game", "title", "timestamp", "createdAt" FROM "temporary_highlight"`);
    await queryRunner.query(`DROP TABLE "temporary_highlight"`);
    await queryRunner.query(`DROP INDEX "IDX_8a80a3cf6b2d815920a390968a"`);
    await queryRunner.query(`ALTER TABLE "event_list" RENAME TO "temporary_event_list"`);
    await queryRunner.query(`CREATE TABLE "event_list" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "event" varchar NOT NULL, "userId" varchar NOT NULL, "timestamp" bigint NOT NULL, "values_json" text NOT NULL, "isTest" boolean NOT NULL, "isHidden" boolean NOT NULL DEFAULT (0))`);
    await queryRunner.query(`INSERT INTO "event_list"("id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden") SELECT "id", "event", "userId", "timestamp", "values_json", "isTest", "isHidden" FROM "temporary_event_list"`);
    await queryRunner.query(`DROP TABLE "temporary_event_list"`);
    await queryRunner.query(`CREATE INDEX "IDX_8a80a3cf6b2d815920a390968a" ON "event_list" ("userId") `);
    await queryRunner.query(`DROP INDEX "IDX_2ccf816b1dd74e9a02845c4818"`);
    await queryRunner.query(`ALTER TABLE "commands_count" RENAME TO "temporary_commands_count"`);
    await queryRunner.query(`CREATE TABLE "commands_count" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "command" varchar NOT NULL, "timestamp" bigint NOT NULL)`);
    await queryRunner.query(`INSERT INTO "commands_count"("id", "command", "timestamp") SELECT "id", "command", "timestamp" FROM "temporary_commands_count"`);
    await queryRunner.query(`DROP TABLE "temporary_commands_count"`);
    await queryRunner.query(`CREATE INDEX "IDX_2ccf816b1dd74e9a02845c4818" ON "commands_count" ("command") `);
    await queryRunner.query(`ALTER TABLE "checklist" RENAME TO "temporary_checklist"`);
    await queryRunner.query(`CREATE TABLE "checklist" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "isCompleted" boolean NOT NULL, "value" varchar NOT NULL)`);
    await queryRunner.query(`INSERT INTO "checklist"("id", "isCompleted", "value") SELECT "id", "isCompleted", "value" FROM "temporary_checklist"`);
    await queryRunner.query(`DROP TABLE "temporary_checklist"`);
  }

}
