import { MigrationInterface, QueryRunner } from 'typeorm';

export class initialize1573837107520 implements MigrationInterface {
  name = 'initialize1573837107520';

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('CREATE TABLE `alert` (`id` varchar(36) NOT NULL, `updatedAt` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `alertDelayInMs` int NOT NULL, `profanityFilterType` varchar(255) NOT NULL, `loadStandardProfanityList` text NOT NULL, `customProfanityList` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_media` (`primaryId` int NOT NULL AUTO_INCREMENT, `id` varchar(255) NOT NULL, `b64data` text NOT NULL, `chunkNo` int NOT NULL, INDEX `IDX_b0f12c32653ed88fd576d3520c` (`id`), PRIMARY KEY (`primaryId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_follow` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_sub` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_subgift` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_host` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, `showAutoHost` tinyint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_raid` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, `showAutoHost` tinyint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_tip` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, `message` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_cheer` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, `message` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alert_resub` (`id` varchar(36) NOT NULL, `alertId` varchar(255) NULL, `enabled` tinyint NOT NULL, `title` varchar(255) NOT NULL, `variantCondition` varchar(255) NOT NULL, `variantAmount` int NOT NULL, `messageTemplate` varchar(255) NOT NULL, `layout` varchar(255) NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOut` varchar(255) NOT NULL, `animationText` varchar(255) NOT NULL, `animationTextOptions` text NOT NULL, `imageId` varchar(255) NOT NULL, `soundId` varchar(255) NOT NULL, `soundVolume` int NOT NULL, `alertDurationInMs` int NOT NULL, `alertTextDelayInMs` int NOT NULL, `enableAdvancedMode` tinyint NOT NULL, `advancedMode` text NOT NULL, `tts` text NOT NULL, `font` text NOT NULL, `message` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `alias` (`id` varchar(36) NOT NULL, `alias` varchar(255) NOT NULL, `command` varchar(255) NOT NULL, `enabled` tinyint NOT NULL, `visible` tinyint NOT NULL, `permission` varchar(255) NOT NULL, INDEX `IDX_6a8a594f0a5546f8082b0c405c` (`alias`), INDEX `IDX_ed5fcb69444dcb0abf0a71053b` (`command`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `bets` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` bigint NOT NULL, `endedAt` bigint NOT NULL, `isLocked` tinyint NOT NULL DEFAULT 0, `arePointsGiven` tinyint NOT NULL DEFAULT 0, `options` text NOT NULL, `title` varchar(255) NOT NULL, INDEX `IDX_df40819eb0eb71d2cc7d73cea8` (`createdAt`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `bets_participations` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `username` varchar(255) NOT NULL, `points` bigint NOT NULL, `optionIdx` bigint NOT NULL, `betId` int NULL, INDEX `IDX_eb26a8222f1ed29abbef861295` (`userId`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `cache_emotes` (`id` varchar(36) NOT NULL, `code` varchar(255) NOT NULL, `type` varchar(6) NOT NULL, `urls` text NOT NULL, INDEX `IDX_36cd5732ccfc2693662be974f9` (`code`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `cache_games` (`id` int NOT NULL, `name` varchar(255) NOT NULL, INDEX `IDX_f37be3c66dbd449a8cb4fe7d59` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `cache_titles` (`id` int NOT NULL AUTO_INCREMENT, `game` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, `timestamp` bigint NOT NULL, INDEX `IDX_a0c6ce833b5b3b13325e6f49b0` (`game`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `carousel` (`id` varchar(36) NOT NULL, `order` int NOT NULL, `type` varchar(255) NOT NULL, `waitBefore` int NOT NULL, `waitAfter` int NOT NULL, `duration` int NOT NULL, `animationInDuration` int NOT NULL, `animationIn` varchar(255) NOT NULL, `animationOutDuration` int NOT NULL, `animationOut` varchar(255) NOT NULL, `showOnlyOncePerStream` tinyint NOT NULL, `base64` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `changelog` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL DEFAULT 0, `threadId` varchar(255) NOT NULL, `namespace` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `checklist` (`id` int NOT NULL AUTO_INCREMENT, `isCompleted` tinyint NOT NULL, `value` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `commands` (`id` varchar(36) NOT NULL, `command` varchar(255) NOT NULL, `enabled` tinyint NOT NULL, `visible` tinyint NOT NULL, INDEX `IDX_1a8c40f0a581447776c325cb4f` (`command`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `commands_responses` (`id` varchar(36) NOT NULL, `order` int NOT NULL, `response` varchar(255) NOT NULL, `stopIfExecuted` tinyint NOT NULL, `permission` varchar(255) NOT NULL, `filter` varchar(255) NOT NULL, `commandId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `commands_count` (`id` int NOT NULL AUTO_INCREMENT, `command` varchar(255) NOT NULL, `timestamp` bigint NOT NULL, INDEX `IDX_2ccf816b1dd74e9a02845c4818` (`command`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `commands_board` (`id` varchar(36) NOT NULL, `order` int NOT NULL, `text` varchar(255) NOT NULL, `command` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `cooldown` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `miliseconds` int NOT NULL, `type` varchar(10) NOT NULL, `timestamp` bigint NOT NULL DEFAULT 0, `lastTimestamp` bigint NOT NULL DEFAULT 0, `isErrorMsgQuiet` tinyint NOT NULL, `isEnabled` tinyint NOT NULL, `isOwnerAffected` tinyint NOT NULL, `isModeratorAffected` tinyint NOT NULL, `isSubscriberAffected` tinyint NOT NULL, `isFollowerAffected` tinyint NOT NULL, UNIQUE INDEX `IDX_aa85aa267ec6eaddf7f93e3665` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `cooldown_viewer` (`id` varchar(36) NOT NULL, `username` varchar(255) NOT NULL, `timestamp` bigint NOT NULL, `lastTimestamp` bigint NOT NULL, `cooldownId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `dashboard` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `createdAt` bigint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `widget` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `positionX` int NOT NULL, `positionY` int NOT NULL, `height` int NOT NULL, `width` int NOT NULL, `dashboardId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `duel` (`id` int NOT NULL, `username` varchar(255) NOT NULL, `tickets` int NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `event` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `givenName` varchar(255) NOT NULL, `isEnabled` tinyint NOT NULL, `triggered` text NOT NULL, `definitions` text NOT NULL, `filter` varchar(255) NOT NULL, INDEX `IDX_b535fbe8ec6d832dde22065ebd` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `event_operation` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `definitions` text NOT NULL, `eventId` varchar(36) NULL, INDEX `IDX_daf6b97e1e5a5c779055fbb22d` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `event_list` (`id` int NOT NULL AUTO_INCREMENT, `event` varchar(255) NOT NULL, `username` varchar(255) NOT NULL, `timestamp` bigint NOT NULL, `values_json` varchar(255) NOT NULL, INDEX `IDX_8a80a3cf6b2d815920a390968a` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `gallery` (`id` varchar(36) NOT NULL, `type` varchar(255) NOT NULL, `data` text NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `goal_group` (`id` varchar(36) NOT NULL, `createdAt` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `display` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `goal` (`id` varchar(36) NOT NULL, `groupId` varchar(255) NULL, `name` varchar(255) NOT NULL, `type` varchar(20) NOT NULL, `countBitsAsTips` tinyint NOT NULL, `display` varchar(20) NOT NULL, `timestamp` bigint NOT NULL DEFAULT 0, `goalAmount` float NOT NULL DEFAULT 0, `currentAmount` float NOT NULL DEFAULT 0, `endAfter` varchar(255) NOT NULL, `endAfterIgnore` tinyint NOT NULL, `customizationBar` text NOT NULL, `customizationFont` text NOT NULL, `customizationHtml` text NOT NULL, `customizationJs` text NOT NULL, `customizationCss` text NOT NULL, INDEX `IDX_a1a6bd23cb8ef7ddf921f54c0b` (`groupId`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `heist_user` (`userId` int NOT NULL, `username` varchar(255) NOT NULL, `points` bigint NOT NULL, PRIMARY KEY (`userId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `highlight` (`id` int NOT NULL AUTO_INCREMENT, `videoId` varchar(255) NOT NULL, `game` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, `timestamp` text NOT NULL, `createdAt` bigint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `how_long_to_beat_game` (`id` int NOT NULL AUTO_INCREMENT, `game` varchar(255) NOT NULL, `startedAt` bigint NOT NULL DEFAULT 0, `isFinishedMain` tinyint NOT NULL, `isFinishedCompletionist` tinyint NOT NULL, `timeToBeatMain` bigint NOT NULL DEFAULT 0, `timeToBeatCompletionist` bigint NOT NULL DEFAULT 0, `gameplayMain` float NOT NULL DEFAULT 0, `gameplayCompletionist` float NOT NULL DEFAULT 0, `imageUrl` varchar(255) NOT NULL, UNIQUE INDEX `IDX_301758e0e3108fc902d5436527` (`game`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `keyword` (`id` varchar(36) NOT NULL, `keyword` varchar(255) NOT NULL, `response` varchar(255) NOT NULL, `enabled` tinyint NOT NULL, INDEX `IDX_35e3ff88225eef1d85c951e229` (`keyword`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `moderation_warning` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `timestamp` bigint NOT NULL DEFAULT 0, INDEX `IDX_f941603aef2741795a9108d0d2` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `moderation_permit` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, INDEX `IDX_69499e78c9ee1602baee77b97d` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `moderation_message_cooldown` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `timestamp` bigint NOT NULL DEFAULT 0, UNIQUE INDEX `IDX_45ad701f0c2955bc09b5661898` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `permissions` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `order` int NOT NULL, `isCorePermission` tinyint NOT NULL, `isWaterfallAllowed` tinyint NOT NULL, `automation` varchar(12) NOT NULL, `userIds` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `permission_filters` (`id` varchar(36) NOT NULL, `comparator` varchar(3) NOT NULL, `type` varchar(255) NOT NULL, `value` bigint NOT NULL, `permissionId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `permission_commands` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `permission` varchar(36) NULL, INDEX `IDX_ba6483f5c5882fa15299f22c0a` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `poll` (`id` varchar(36) NOT NULL, `type` varchar(6) NOT NULL, `title` varchar(255) NOT NULL, `isOpened` tinyint NOT NULL, `openedAt` bigint NOT NULL DEFAULT 0, `closedAt` bigint NOT NULL DEFAULT 0, `options` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `poll_vote` (`id` varchar(36) NOT NULL, `option` int NOT NULL, `votes` int NOT NULL, `votedBy` varchar(255) NOT NULL, `pollId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `price` (`id` varchar(36) NOT NULL, `command` varchar(255) NOT NULL, `enabled` tinyint NOT NULL DEFAULT 1, `price` int NOT NULL, UNIQUE INDEX `IDX_d12db23d28020784096bcb41a3` (`command`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `queue` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` bigint NOT NULL, `username` varchar(255) NOT NULL, `isModerator` tinyint NOT NULL, `isSubscriber` tinyint NOT NULL, `isFollower` tinyint NOT NULL, UNIQUE INDEX `IDX_7401b4e0c30f5de6621b38f7a0` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `quotes` (`id` varchar(36) NOT NULL, `tags` text NOT NULL, `quote` varchar(255) NOT NULL, `quotedBy` int NOT NULL, `createdAt` bigint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `raffle` (`id` varchar(36) NOT NULL, `winner` text NULL, `timestamp` bigint NOT NULL DEFAULT 0, `keyword` varchar(255) NOT NULL, `minTickets` bigint NOT NULL DEFAULT 0, `maxTickets` bigint NOT NULL DEFAULT 0, `type` int NOT NULL, `forFollowers` tinyint NOT NULL, `forSubscribers` tinyint NOT NULL, `isClosed` tinyint NOT NULL DEFAULT 0, INDEX `IDX_e83facaeb8fbe8b8ce9577209a` (`keyword`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `raffle_participant` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `tickets` int NOT NULL, `isEligible` tinyint NOT NULL, `isFollower` tinyint NOT NULL, `isSubscriber` tinyint NOT NULL, `raffleId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `raffle_participant_message` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL DEFAULT 0, `text` text NOT NULL, `participantId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `rank` (`id` varchar(36) NOT NULL, `hours` int NOT NULL, `rank` varchar(255) NOT NULL, UNIQUE INDEX `IDX_93c78c94804a13befdace81904` (`hours`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `scrim_match_id` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `matchId` varchar(255) NOT NULL, UNIQUE INDEX `IDX_5af6da125c1745151e0dfaf087` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `settings` (`id` int NOT NULL AUTO_INCREMENT, `namespace` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `value` text NOT NULL, INDEX `IDX_d8a83b9ffce680092c8dfee37d` (`namespace`), INDEX `IDX_ca7857276d2a30f4dcfa0e42cd` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `song_playlist` (`videoId` varchar(255) NOT NULL, `lastPlayedAt` bigint NOT NULL DEFAULT 0, `seed` float NOT NULL, `title` varchar(255) NOT NULL, `loudness` float NOT NULL, `length` int NOT NULL, `forceVolume` tinyint NOT NULL DEFAULT 0, `volume` int NOT NULL, `startTime` int NOT NULL, `endTime` int NOT NULL, PRIMARY KEY (`videoId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `song_request` (`videoId` varchar(255) NOT NULL, `addedAt` bigint NOT NULL DEFAULT 0, `title` varchar(255) NOT NULL, `loudness` float NOT NULL, `length` int NOT NULL, `username` varchar(255) NOT NULL, PRIMARY KEY (`videoId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `song_ban` (`videoId` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, PRIMARY KEY (`videoId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `text` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `text` text NOT NULL, `css` text NOT NULL, `js` text NOT NULL, `external` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `thread_event` (`id` int NOT NULL AUTO_INCREMENT, `event` varchar(255) NOT NULL, INDEX `IDX_b8f5d0db148b37b4791a5e22c1` (`event`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `timer` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `isEnabled` tinyint NOT NULL, `triggerEveryMessage` int NOT NULL, `triggerEverySecond` int NOT NULL, `triggeredAtTimestamp` bigint NOT NULL DEFAULT 0, `triggeredAtMessages` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `timer_response` (`id` varchar(36) NOT NULL, `timestamp` bigint NOT NULL DEFAULT 0, `isEnabled` tinyint NOT NULL DEFAULT 1, `response` text NOT NULL, `timerId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `translation` (`value` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`name`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `twitch_tag` (`tag_id` varchar(255) NOT NULL, `is_auto` tinyint NOT NULL, `is_current` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (`tag_id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `twitch_tag_localization_name` (`id` varchar(36) NOT NULL, `locale` varchar(255) NOT NULL, `value` varchar(255) NOT NULL, `tagId` varchar(255) NULL, INDEX `IDX_dcf417a56c907f3a6788476047` (`tagId`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `twitch_tag_localization_description` (`id` varchar(36) NOT NULL, `locale` varchar(255) NOT NULL, `value` varchar(255) NOT NULL, `tagId` varchar(255) NULL, INDEX `IDX_4d8108fc3e8dcbe5c112f53dd3` (`tagId`), PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `twitch_stats` (`whenOnline` bigint NOT NULL, `currentViewers` int NOT NULL DEFAULT 0, `currentSubscribers` int NOT NULL DEFAULT 0, `currentBits` bigint NOT NULL, `currentTips` float NOT NULL, `chatMessages` bigint NOT NULL, `currentFollowers` int NOT NULL DEFAULT 0, `currentViews` int NOT NULL DEFAULT 0, `maxViewers` int NOT NULL DEFAULT 0, `currentHosts` int NOT NULL DEFAULT 0, `newChatters` int NOT NULL DEFAULT 0, `currentWatched` bigint NOT NULL, PRIMARY KEY (`whenOnline`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `twitch_clips` (`clipId` varchar(255) NOT NULL, `isChecked` tinyint NOT NULL, `shouldBeCheckedAt` bigint NOT NULL, PRIMARY KEY (`clipId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `user` (`userId` int NOT NULL, `username` varchar(255) NOT NULL, `displayname` varchar(255) NOT NULL DEFAULT \'\', `profileImageUrl` varchar(255) NOT NULL DEFAULT \'\', `isOnline` tinyint NOT NULL DEFAULT 0, `isVIP` tinyint NOT NULL DEFAULT 0, `isFollower` tinyint NOT NULL DEFAULT 0, `isModerator` tinyint NOT NULL DEFAULT 0, `isSubscriber` tinyint NOT NULL DEFAULT 0, `haveSubscriberLock` tinyint NOT NULL DEFAULT 0, `haveFollowerLock` tinyint NOT NULL DEFAULT 0, `haveSubscribedAtLock` tinyint NOT NULL DEFAULT 0, `haveFollowedAtLock` tinyint NOT NULL DEFAULT 0, `rank` varchar(255) NOT NULL DEFAULT \'\', `haveCustomRank` tinyint NOT NULL DEFAULT 0, `followedAt` bigint NOT NULL DEFAULT 0, `followCheckAt` bigint NOT NULL DEFAULT 0, `subscribedAt` bigint NOT NULL DEFAULT 0, `seenAt` bigint NOT NULL DEFAULT 0, `createdAt` bigint NOT NULL DEFAULT 0, `watchedTime` bigint NOT NULL DEFAULT 0, `chatTimeOnline` bigint NOT NULL DEFAULT 0, `chatTimeOffline` bigint NOT NULL DEFAULT 0, `points` bigint NOT NULL DEFAULT 0, `pointsOnlineGivenAt` bigint NOT NULL DEFAULT 0, `pointsOfflineGivenAt` bigint NOT NULL DEFAULT 0, `pointsByMessageGivenAt` bigint NOT NULL DEFAULT 0, `subscribeTier` varchar(255) NOT NULL DEFAULT \'0\', `subscribeCumulativeMonths` int NOT NULL DEFAULT 0, `subscribeStreak` int NOT NULL DEFAULT 0, `giftedSubscribes` bigint NOT NULL DEFAULT 0, `messages` bigint NOT NULL DEFAULT 0, INDEX `IDX_78a916df40e02a9deb1c4b75ed` (`username`), PRIMARY KEY (`userId`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `user_tip` (`id` int NOT NULL AUTO_INCREMENT, `amount` float NOT NULL, `currency` varchar(255) NOT NULL, `message` varchar(255) NOT NULL DEFAULT \'\', `tippedAt` bigint NOT NULL DEFAULT 0, `sortAmount` float NOT NULL, `userUserId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `user_bit` (`id` int NOT NULL AUTO_INCREMENT, `amount` bigint NOT NULL, `message` varchar(255) NOT NULL DEFAULT \'\', `cheeredAt` bigint NOT NULL DEFAULT 0, `userUserId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `variable` (`id` varchar(36) NOT NULL, `variableName` varchar(255) NOT NULL, `description` varchar(255) NOT NULL DEFAULT \'\', `type` varchar(255) NOT NULL, `currentValue` varchar(255) NOT NULL, `evalValue` text NOT NULL, `runEveryTypeValue` int NOT NULL DEFAULT 60000, `runEveryType` varchar(255) NOT NULL DEFAULT \'isUsed\', `runEvery` int NOT NULL DEFAULT 60000, `responseType` int NOT NULL, `responseText` varchar(255) NOT NULL DEFAULT \'\', `permission` varchar(255) NOT NULL, `readOnly` tinyint NOT NULL DEFAULT 0, `usableOptions` text NOT NULL, `runAt` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `variable_history` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL DEFAULT 0, `username` varchar(255) NOT NULL DEFAULT \'n/a\', `currentValue` varchar(255) NOT NULL, `oldValue` text NOT NULL, `changedAt` bigint NOT NULL DEFAULT 0, `variableId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `variable_url` (`id` varchar(36) NOT NULL, `GET` tinyint NOT NULL DEFAULT 0, `POST` tinyint NOT NULL DEFAULT 0, `showResponse` tinyint NOT NULL DEFAULT 0, `variableId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `variable_watch` (`id` int NOT NULL AUTO_INCREMENT, `variableId` varchar(255) NOT NULL, `order` int NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('CREATE TABLE `widget_social` (`id` varchar(255) NOT NULL, `type` varchar(255) NOT NULL, `hashtag` varchar(255) NOT NULL, `text` text NOT NULL, `username` varchar(255) NOT NULL, `displayname` varchar(255) NOT NULL, `url` varchar(255) NOT NULL, `timestamp` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
    await queryRunner.query('ALTER TABLE `alert_follow` ADD CONSTRAINT `FK_6e7a73361ade12e7e69040a7c07` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_sub` ADD CONSTRAINT `FK_52aaa81fff666f516b021774b60` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_subgift` ADD CONSTRAINT `FK_79f7ce25e52da9ab0085b237c52` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_host` ADD CONSTRAINT `FK_c665ba36c06d60912fdaf8bb9cc` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_raid` ADD CONSTRAINT `FK_aa40fffe0016d3700315f5b4c24` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_tip` ADD CONSTRAINT `FK_05e3dcbf185b77f33cc4078dba2` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_cheer` ADD CONSTRAINT `FK_09f1fb76339fc4afffc74b37db7` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `alert_resub` ADD CONSTRAINT `FK_25ce77691f1aa94d954c0f88ecd` FOREIGN KEY (`alertId`) REFERENCES `alert`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `bets_participations` ADD CONSTRAINT `FK_f4888a939a9c39297bd786c5e9c` FOREIGN KEY (`betId`) REFERENCES `bets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `commands_responses` ADD CONSTRAINT `FK_09da90fa3264f486de9be57b185` FOREIGN KEY (`commandId`) REFERENCES `commands`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `cooldown_viewer` ADD CONSTRAINT `FK_5ba6ccf5a51426111e322c80445` FOREIGN KEY (`cooldownId`) REFERENCES `cooldown`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `widget` ADD CONSTRAINT `FK_95877f9f08f5663fd6a177c5a0e` FOREIGN KEY (`dashboardId`) REFERENCES `dashboard`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `event_operation` ADD CONSTRAINT `FK_a9f07bd7a9f0b7b9d41f48b476d` FOREIGN KEY (`eventId`) REFERENCES `event`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `goal` ADD CONSTRAINT `FK_a1a6bd23cb8ef7ddf921f54c0bb` FOREIGN KEY (`groupId`) REFERENCES `goal_group`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `permission_filters` ADD CONSTRAINT `FK_58a2c7864182d942bea393b4420` FOREIGN KEY (`permissionId`) REFERENCES `permissions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `poll_vote` ADD CONSTRAINT `FK_99f9db6d3dae2a0aebebbf8e10a` FOREIGN KEY (`pollId`) REFERENCES `poll`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `raffle_participant` ADD CONSTRAINT `FK_bc112542267bdd487f4479a94a1` FOREIGN KEY (`raffleId`) REFERENCES `raffle`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD CONSTRAINT `FK_e6eda53bcd6ceb62b5edd9e02b5` FOREIGN KEY (`participantId`) REFERENCES `raffle_participant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `timer_response` ADD CONSTRAINT `FK_3192b176b66d4375368c9e960de` FOREIGN KEY (`timerId`) REFERENCES `timer`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `twitch_tag_localization_name` ADD CONSTRAINT `FK_dcf417a56c907f3a6788476047b` FOREIGN KEY (`tagId`) REFERENCES `twitch_tag`(`tag_id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `twitch_tag_localization_description` ADD CONSTRAINT `FK_4d8108fc3e8dcbe5c112f53dd3f` FOREIGN KEY (`tagId`) REFERENCES `twitch_tag`(`tag_id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `user_tip` ADD CONSTRAINT `FK_36683fb221201263b38344a9880` FOREIGN KEY (`userUserId`) REFERENCES `user`(`userId`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `user_bit` ADD CONSTRAINT `FK_cca96526faa532e7d20a0f775b0` FOREIGN KEY (`userUserId`) REFERENCES `user`(`userId`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `variable_history` ADD CONSTRAINT `FK_94d39c77652e9c332751a0cee02` FOREIGN KEY (`variableId`) REFERENCES `variable`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('ALTER TABLE `variable_url` ADD CONSTRAINT `FK_806e97dff1efce7f8872b6d4500` FOREIGN KEY (`variableId`) REFERENCES `variable`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', undefined);
    await queryRunner.query('CREATE TABLE `query-result-cache` (`id` int NOT NULL AUTO_INCREMENT, `identifier` varchar(255) NULL, `time` bigint NOT NULL, `duration` int NOT NULL, `query` text NOT NULL, `result` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('DROP TABLE `query-result-cache`', undefined);
    await queryRunner.query('ALTER TABLE `variable_url` DROP FOREIGN KEY `FK_806e97dff1efce7f8872b6d4500`', undefined);
    await queryRunner.query('ALTER TABLE `variable_history` DROP FOREIGN KEY `FK_94d39c77652e9c332751a0cee02`', undefined);
    await queryRunner.query('ALTER TABLE `user_bit` DROP FOREIGN KEY `FK_cca96526faa532e7d20a0f775b0`', undefined);
    await queryRunner.query('ALTER TABLE `user_tip` DROP FOREIGN KEY `FK_36683fb221201263b38344a9880`', undefined);
    await queryRunner.query('ALTER TABLE `twitch_tag_localization_description` DROP FOREIGN KEY `FK_4d8108fc3e8dcbe5c112f53dd3f`', undefined);
    await queryRunner.query('ALTER TABLE `twitch_tag_localization_name` DROP FOREIGN KEY `FK_dcf417a56c907f3a6788476047b`', undefined);
    await queryRunner.query('ALTER TABLE `timer_response` DROP FOREIGN KEY `FK_3192b176b66d4375368c9e960de`', undefined);
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP FOREIGN KEY `FK_e6eda53bcd6ceb62b5edd9e02b5`', undefined);
    await queryRunner.query('ALTER TABLE `raffle_participant` DROP FOREIGN KEY `FK_bc112542267bdd487f4479a94a1`', undefined);
    await queryRunner.query('ALTER TABLE `poll_vote` DROP FOREIGN KEY `FK_99f9db6d3dae2a0aebebbf8e10a`', undefined);
    await queryRunner.query('ALTER TABLE `permission_filters` DROP FOREIGN KEY `FK_58a2c7864182d942bea393b4420`', undefined);
    await queryRunner.query('ALTER TABLE `goal` DROP FOREIGN KEY `FK_a1a6bd23cb8ef7ddf921f54c0bb`', undefined);
    await queryRunner.query('ALTER TABLE `event_operation` DROP FOREIGN KEY `FK_a9f07bd7a9f0b7b9d41f48b476d`', undefined);
    await queryRunner.query('ALTER TABLE `widget` DROP FOREIGN KEY `FK_95877f9f08f5663fd6a177c5a0e`', undefined);
    await queryRunner.query('ALTER TABLE `cooldown_viewer` DROP FOREIGN KEY `FK_5ba6ccf5a51426111e322c80445`', undefined);
    await queryRunner.query('ALTER TABLE `commands_responses` DROP FOREIGN KEY `FK_09da90fa3264f486de9be57b185`', undefined);
    await queryRunner.query('ALTER TABLE `bets_participations` DROP FOREIGN KEY `FK_f4888a939a9c39297bd786c5e9c`', undefined);
    await queryRunner.query('ALTER TABLE `alert_resub` DROP FOREIGN KEY `FK_25ce77691f1aa94d954c0f88ecd`', undefined);
    await queryRunner.query('ALTER TABLE `alert_cheer` DROP FOREIGN KEY `FK_09f1fb76339fc4afffc74b37db7`', undefined);
    await queryRunner.query('ALTER TABLE `alert_tip` DROP FOREIGN KEY `FK_05e3dcbf185b77f33cc4078dba2`', undefined);
    await queryRunner.query('ALTER TABLE `alert_raid` DROP FOREIGN KEY `FK_aa40fffe0016d3700315f5b4c24`', undefined);
    await queryRunner.query('ALTER TABLE `alert_host` DROP FOREIGN KEY `FK_c665ba36c06d60912fdaf8bb9cc`', undefined);
    await queryRunner.query('ALTER TABLE `alert_subgift` DROP FOREIGN KEY `FK_79f7ce25e52da9ab0085b237c52`', undefined);
    await queryRunner.query('ALTER TABLE `alert_sub` DROP FOREIGN KEY `FK_52aaa81fff666f516b021774b60`', undefined);
    await queryRunner.query('ALTER TABLE `alert_follow` DROP FOREIGN KEY `FK_6e7a73361ade12e7e69040a7c07`', undefined);
    await queryRunner.query('DROP TABLE `widget_social`', undefined);
    await queryRunner.query('DROP TABLE `variable_watch`', undefined);
    await queryRunner.query('DROP TABLE `variable_url`', undefined);
    await queryRunner.query('DROP TABLE `variable_history`', undefined);
    await queryRunner.query('DROP TABLE `variable`', undefined);
    await queryRunner.query('DROP TABLE `user_bit`', undefined);
    await queryRunner.query('DROP TABLE `user_tip`', undefined);
    await queryRunner.query('DROP INDEX `IDX_78a916df40e02a9deb1c4b75ed` ON `user`', undefined);
    await queryRunner.query('DROP TABLE `user`', undefined);
    await queryRunner.query('DROP TABLE `twitch_clips`', undefined);
    await queryRunner.query('DROP TABLE `twitch_stats`', undefined);
    await queryRunner.query('DROP INDEX `IDX_4d8108fc3e8dcbe5c112f53dd3` ON `twitch_tag_localization_description`', undefined);
    await queryRunner.query('DROP TABLE `twitch_tag_localization_description`', undefined);
    await queryRunner.query('DROP INDEX `IDX_dcf417a56c907f3a6788476047` ON `twitch_tag_localization_name`', undefined);
    await queryRunner.query('DROP TABLE `twitch_tag_localization_name`', undefined);
    await queryRunner.query('DROP TABLE `twitch_tag`', undefined);
    await queryRunner.query('DROP TABLE `translation`', undefined);
    await queryRunner.query('DROP TABLE `timer_response`', undefined);
    await queryRunner.query('DROP TABLE `timer`', undefined);
    await queryRunner.query('DROP INDEX `IDX_b8f5d0db148b37b4791a5e22c1` ON `thread_event`', undefined);
    await queryRunner.query('DROP TABLE `thread_event`', undefined);
    await queryRunner.query('DROP TABLE `text`', undefined);
    await queryRunner.query('DROP TABLE `song_ban`', undefined);
    await queryRunner.query('DROP TABLE `song_request`', undefined);
    await queryRunner.query('DROP TABLE `song_playlist`', undefined);
    await queryRunner.query('DROP INDEX `IDX_ca7857276d2a30f4dcfa0e42cd` ON `settings`', undefined);
    await queryRunner.query('DROP INDEX `IDX_d8a83b9ffce680092c8dfee37d` ON `settings`', undefined);
    await queryRunner.query('DROP TABLE `settings`', undefined);
    await queryRunner.query('DROP INDEX `IDX_5af6da125c1745151e0dfaf087` ON `scrim_match_id`', undefined);
    await queryRunner.query('DROP TABLE `scrim_match_id`', undefined);
    await queryRunner.query('DROP INDEX `IDX_93c78c94804a13befdace81904` ON `rank`', undefined);
    await queryRunner.query('DROP TABLE `rank`', undefined);
    await queryRunner.query('DROP TABLE `raffle_participant_message`', undefined);
    await queryRunner.query('DROP TABLE `raffle_participant`', undefined);
    await queryRunner.query('DROP INDEX `IDX_e83facaeb8fbe8b8ce9577209a` ON `raffle`', undefined);
    await queryRunner.query('DROP TABLE `raffle`', undefined);
    await queryRunner.query('DROP TABLE `quotes`', undefined);
    await queryRunner.query('DROP INDEX `IDX_7401b4e0c30f5de6621b38f7a0` ON `queue`', undefined);
    await queryRunner.query('DROP TABLE `queue`', undefined);
    await queryRunner.query('DROP INDEX `IDX_d12db23d28020784096bcb41a3` ON `price`', undefined);
    await queryRunner.query('DROP TABLE `price`', undefined);
    await queryRunner.query('DROP TABLE `poll_vote`', undefined);
    await queryRunner.query('DROP TABLE `poll`', undefined);
    await queryRunner.query('DROP INDEX `IDX_ba6483f5c5882fa15299f22c0a` ON `permission_commands`', undefined);
    await queryRunner.query('DROP TABLE `permission_commands`', undefined);
    await queryRunner.query('DROP TABLE `permission_filters`', undefined);
    await queryRunner.query('DROP TABLE `permissions`', undefined);
    await queryRunner.query('DROP INDEX `IDX_45ad701f0c2955bc09b5661898` ON `moderation_message_cooldown`', undefined);
    await queryRunner.query('DROP TABLE `moderation_message_cooldown`', undefined);
    await queryRunner.query('DROP INDEX `IDX_69499e78c9ee1602baee77b97d` ON `moderation_permit`', undefined);
    await queryRunner.query('DROP TABLE `moderation_permit`', undefined);
    await queryRunner.query('DROP INDEX `IDX_f941603aef2741795a9108d0d2` ON `moderation_warning`', undefined);
    await queryRunner.query('DROP TABLE `moderation_warning`', undefined);
    await queryRunner.query('DROP INDEX `IDX_35e3ff88225eef1d85c951e229` ON `keyword`', undefined);
    await queryRunner.query('DROP TABLE `keyword`', undefined);
    await queryRunner.query('DROP INDEX `IDX_301758e0e3108fc902d5436527` ON `how_long_to_beat_game`', undefined);
    await queryRunner.query('DROP TABLE `how_long_to_beat_game`', undefined);
    await queryRunner.query('DROP TABLE `highlight`', undefined);
    await queryRunner.query('DROP TABLE `heist_user`', undefined);
    await queryRunner.query('DROP INDEX `IDX_a1a6bd23cb8ef7ddf921f54c0b` ON `goal`', undefined);
    await queryRunner.query('DROP TABLE `goal`', undefined);
    await queryRunner.query('DROP TABLE `goal_group`', undefined);
    await queryRunner.query('DROP TABLE `gallery`', undefined);
    await queryRunner.query('DROP INDEX `IDX_8a80a3cf6b2d815920a390968a` ON `event_list`', undefined);
    await queryRunner.query('DROP TABLE `event_list`', undefined);
    await queryRunner.query('DROP INDEX `IDX_daf6b97e1e5a5c779055fbb22d` ON `event_operation`', undefined);
    await queryRunner.query('DROP TABLE `event_operation`', undefined);
    await queryRunner.query('DROP INDEX `IDX_b535fbe8ec6d832dde22065ebd` ON `event`', undefined);
    await queryRunner.query('DROP TABLE `event`', undefined);
    await queryRunner.query('DROP TABLE `duel`', undefined);
    await queryRunner.query('DROP TABLE `widget`', undefined);
    await queryRunner.query('DROP TABLE `dashboard`', undefined);
    await queryRunner.query('DROP TABLE `cooldown_viewer`', undefined);
    await queryRunner.query('DROP INDEX `IDX_aa85aa267ec6eaddf7f93e3665` ON `cooldown`', undefined);
    await queryRunner.query('DROP TABLE `cooldown`', undefined);
    await queryRunner.query('DROP TABLE `commands_board`', undefined);
    await queryRunner.query('DROP INDEX `IDX_2ccf816b1dd74e9a02845c4818` ON `commands_count`', undefined);
    await queryRunner.query('DROP TABLE `commands_count`', undefined);
    await queryRunner.query('DROP TABLE `commands_responses`', undefined);
    await queryRunner.query('DROP INDEX `IDX_1a8c40f0a581447776c325cb4f` ON `commands`', undefined);
    await queryRunner.query('DROP TABLE `commands`', undefined);
    await queryRunner.query('DROP TABLE `checklist`', undefined);
    await queryRunner.query('DROP TABLE `changelog`', undefined);
    await queryRunner.query('DROP TABLE `carousel`', undefined);
    await queryRunner.query('DROP INDEX `IDX_a0c6ce833b5b3b13325e6f49b0` ON `cache_titles`', undefined);
    await queryRunner.query('DROP TABLE `cache_titles`', undefined);
    await queryRunner.query('DROP INDEX `IDX_f37be3c66dbd449a8cb4fe7d59` ON `cache_games`', undefined);
    await queryRunner.query('DROP TABLE `cache_games`', undefined);
    await queryRunner.query('DROP INDEX `IDX_36cd5732ccfc2693662be974f9` ON `cache_emotes`', undefined);
    await queryRunner.query('DROP TABLE `cache_emotes`', undefined);
    await queryRunner.query('DROP INDEX `IDX_eb26a8222f1ed29abbef861295` ON `bets_participations`', undefined);
    await queryRunner.query('DROP TABLE `bets_participations`', undefined);
    await queryRunner.query('DROP INDEX `IDX_df40819eb0eb71d2cc7d73cea8` ON `bets`', undefined);
    await queryRunner.query('DROP TABLE `bets`', undefined);
    await queryRunner.query('DROP INDEX `IDX_ed5fcb69444dcb0abf0a71053b` ON `alias`', undefined);
    await queryRunner.query('DROP INDEX `IDX_6a8a594f0a5546f8082b0c405c` ON `alias`', undefined);
    await queryRunner.query('DROP TABLE `alias`', undefined);
    await queryRunner.query('DROP TABLE `alert_resub`', undefined);
    await queryRunner.query('DROP TABLE `alert_cheer`', undefined);
    await queryRunner.query('DROP TABLE `alert_tip`', undefined);
    await queryRunner.query('DROP TABLE `alert_raid`', undefined);
    await queryRunner.query('DROP TABLE `alert_host`', undefined);
    await queryRunner.query('DROP TABLE `alert_subgift`', undefined);
    await queryRunner.query('DROP TABLE `alert_sub`', undefined);
    await queryRunner.query('DROP TABLE `alert_follow`', undefined);
    await queryRunner.query('DROP INDEX `IDX_b0f12c32653ed88fd576d3520c` ON `alert_media`', undefined);
    await queryRunner.query('DROP TABLE `alert_media`', undefined);
    await queryRunner.query('DROP TABLE `alert`', undefined);
  }

}
