import { MigrationInterface, QueryRunner } from 'typeorm';

export class idAlign1602499070261 implements MigrationInterface {
  name = 'idAlign1602499070261';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `checklist` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `checklist` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `checklist` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `checklist` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `commands_count` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `commands_count` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `commands_count` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `commands_count` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `event_list` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `event_list` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `event_list` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `event_list` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `highlight` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `highlight` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `highlight` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `highlight` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `moderation_warning` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `moderation_warning` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `moderation_warning` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `moderation_warning` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `moderation_permit` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `moderation_permit` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `moderation_permit` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `moderation_permit` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `permission_commands` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `permission_commands` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `permission_commands` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `permission_commands` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP FOREIGN KEY `FK_e6eda53bcd6ceb62b5edd9e02b5`');
    await queryRunner.query('ALTER TABLE `raffle_participant` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `raffle_participant` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `raffle_participant` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `raffle_participant` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP COLUMN `participantId`');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD `participantId` varchar(36) NULL');
    await queryRunner.query('ALTER TABLE `scrim_match_id` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `scrim_match_id` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `scrim_match_id` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `scrim_match_id` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `thread_event` CHANGE `id` `id` int NOT NULL');
    await queryRunner.query('ALTER TABLE `thread_event` DROP PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `thread_event` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `thread_event` ADD `id` varchar(36) NOT NULL PRIMARY KEY');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD CONSTRAINT `FK_e6eda53bcd6ceb62b5edd9e02b5` FOREIGN KEY (`participantId`) REFERENCES `raffle_participant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP FOREIGN KEY `FK_e6eda53bcd6ceb62b5edd9e02b5`');
    await queryRunner.query('ALTER TABLE `thread_event` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `thread_event` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `thread_event` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `thread_event` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `scrim_match_id` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `scrim_match_id` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `scrim_match_id` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `scrim_match_id` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP COLUMN `participantId`');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD `participantId` int NULL');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `raffle_participant` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `raffle_participant` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `raffle_participant` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `raffle_participant` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `raffle_participant_message` ADD CONSTRAINT `FK_e6eda53bcd6ceb62b5edd9e02b5` FOREIGN KEY (`participantId`) REFERENCES `raffle_participant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE');
    await queryRunner.query('ALTER TABLE `permission_commands` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `permission_commands` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `permission_commands` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `permission_commands` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `moderation_message_cooldown` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `moderation_permit` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `moderation_permit` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `moderation_permit` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `moderation_permit` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `moderation_warning` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `moderation_warning` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `moderation_warning` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `moderation_warning` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `how_long_to_beat_game` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `highlight` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `highlight` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `highlight` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `highlight` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `event_list` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `event_list` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `event_list` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `event_list` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `commands_count` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `commands_count` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `commands_count` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `commands_count` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `checklist` DROP COLUMN `id`');
    await queryRunner.query('ALTER TABLE `checklist` ADD `id` int NOT NULL AUTO_INCREMENT');
    await queryRunner.query('ALTER TABLE `checklist` ADD PRIMARY KEY (`id`)');
    await queryRunner.query('ALTER TABLE `checklist` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT');
  }

}