import {MigrationInterface, QueryRunner} from 'typeorm';

export class schemaAlign1578656877001 implements MigrationInterface {
  name = 'schemaAlign1578656877001';

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`DROP INDEX "IDX_a1a6bd23cb8ef7ddf921f54c0b"`, undefined);
    await queryRunner.query(`CREATE TABLE "temporary_goal" ("id" varchar PRIMARY KEY NOT NULL, "groupId" varchar, "name" varchar NOT NULL, "type" varchar(20) NOT NULL, "countBitsAsTips" boolean NOT NULL, "display" varchar(20) NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "goalAmount" float(12) NOT NULL DEFAULT (0), "currentAmount" float(12) NOT NULL DEFAULT (0), "endAfter" varchar NOT NULL, "endAfterIgnore" boolean NOT NULL, "customizationBar" text NOT NULL, "customizationFont" text NOT NULL, "customizationHtml" text NOT NULL, "customizationJs" text NOT NULL, "customizationCss" text NOT NULL, CONSTRAINT "FK_a1a6bd23cb8ef7ddf921f54c0bb" FOREIGN KEY ("groupId") REFERENCES "goal_group" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`, undefined);
    await queryRunner.query(`INSERT INTO "temporary_goal"("id", "groupId", "name", "type", "countBitsAsTips", "display", "timestamp", "goalAmount", "currentAmount", "endAfter", "endAfterIgnore", "customizationBar", "customizationFont", "customizationHtml", "customizationJs", "customizationCss") SELECT "id", "groupId", "name", "type", "countBitsAsTips", "display", "timestamp", "goalAmount", "currentAmount", "endAfter", "endAfterIgnore", "customizationBar", "customizationFont", "customizationHtml", "customizationJs", "customizationCss" FROM "goal"`, undefined);
    await queryRunner.query(`DROP TABLE "goal"`, undefined);
    await queryRunner.query(`ALTER TABLE "temporary_goal" RENAME TO "goal"`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_a1a6bd23cb8ef7ddf921f54c0b" ON "goal" ("groupId") `, undefined);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`, undefined);
    await queryRunner.query(`CREATE TABLE "temporary_how_long_to_beat_game" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "game" varchar NOT NULL, "startedAt" bigint NOT NULL DEFAULT (0), "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT (0), "timeToBeatCompletionist" bigint NOT NULL DEFAULT (0), "gameplayMain" float(12) NOT NULL DEFAULT (0), "gameplayCompletionist" float(12) NOT NULL DEFAULT (0), "imageUrl" varchar NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "temporary_how_long_to_beat_game"("id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl") SELECT "id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl" FROM "how_long_to_beat_game"`, undefined);
    await queryRunner.query(`DROP TABLE "how_long_to_beat_game"`, undefined);
    await queryRunner.query(`ALTER TABLE "temporary_how_long_to_beat_game" RENAME TO "how_long_to_beat_game"`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `, undefined);
    await queryRunner.query(`CREATE TABLE "temporary_song_playlist" ("videoId" varchar PRIMARY KEY NOT NULL, "lastPlayedAt" bigint NOT NULL DEFAULT (0), "seed" float(12) NOT NULL, "title" varchar NOT NULL, "loudness" float(12) NOT NULL, "length" integer NOT NULL, "forceVolume" boolean NOT NULL DEFAULT (0), "volume" integer NOT NULL, "startTime" integer NOT NULL, "endTime" integer NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "temporary_song_playlist"("videoId", "lastPlayedAt", "seed", "title", "loudness", "length", "forceVolume", "volume", "startTime", "endTime") SELECT "videoId", "lastPlayedAt", "seed", "title", "loudness", "length", "forceVolume", "volume", "startTime", "endTime" FROM "song_playlist"`, undefined);
    await queryRunner.query(`DROP TABLE "song_playlist"`, undefined);
    await queryRunner.query(`ALTER TABLE "temporary_song_playlist" RENAME TO "song_playlist"`, undefined);
    await queryRunner.query(`CREATE TABLE "temporary_song_request" ("videoId" varchar NOT NULL, "addedAt" bigint NOT NULL DEFAULT (0), "title" varchar NOT NULL, "loudness" float(12) NOT NULL, "length" integer NOT NULL, "username" varchar NOT NULL, "id" varchar PRIMARY KEY NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "temporary_song_request"("videoId", "addedAt", "title", "loudness", "length", "username", "id") SELECT "videoId", "addedAt", "title", "loudness", "length", "username", "id" FROM "song_request"`, undefined);
    await queryRunner.query(`DROP TABLE "song_request"`, undefined);
    await queryRunner.query(`ALTER TABLE "temporary_song_request" RENAME TO "song_request"`, undefined);
    await queryRunner.query(`CREATE TABLE "temporary_twitch_stats" ("whenOnline" bigint PRIMARY KEY NOT NULL, "currentViewers" integer NOT NULL DEFAULT (0), "currentSubscribers" integer NOT NULL DEFAULT (0), "currentBits" bigint NOT NULL, "currentTips" float(12) NOT NULL, "chatMessages" bigint NOT NULL, "currentFollowers" integer NOT NULL DEFAULT (0), "currentViews" integer NOT NULL DEFAULT (0), "maxViewers" integer NOT NULL DEFAULT (0), "currentHosts" integer NOT NULL DEFAULT (0), "newChatters" integer NOT NULL DEFAULT (0), "currentWatched" bigint NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "temporary_twitch_stats"("whenOnline", "currentViewers", "currentSubscribers", "currentBits", "currentTips", "chatMessages", "currentFollowers", "currentViews", "maxViewers", "currentHosts", "newChatters", "currentWatched") SELECT "whenOnline", "currentViewers", "currentSubscribers", "currentBits", "currentTips", "chatMessages", "currentFollowers", "currentViews", "maxViewers", "currentHosts", "newChatters", "currentWatched" FROM "twitch_stats"`, undefined);
    await queryRunner.query(`DROP TABLE "twitch_stats"`, undefined);
    await queryRunner.query(`ALTER TABLE "temporary_twitch_stats" RENAME TO "twitch_stats"`, undefined);
    await queryRunner.query(`CREATE TABLE "temporary_user_tip" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "amount" float(12) NOT NULL, "currency" varchar NOT NULL, "message" text NOT NULL DEFAULT (''), "tippedAt" bigint NOT NULL DEFAULT (0), "sortAmount" float(12) NOT NULL, "userUserId" integer, CONSTRAINT "FK_36683fb221201263b38344a9880" FOREIGN KEY ("userUserId") REFERENCES "user" ("userId") ON DELETE CASCADE ON UPDATE CASCADE)`, undefined);
    await queryRunner.query(`INSERT INTO "temporary_user_tip"("id", "amount", "currency", "message", "tippedAt", "sortAmount", "userUserId") SELECT "id", "amount", "currency", "message", "tippedAt", "sortAmount", "userUserId" FROM "user_tip"`, undefined);
    await queryRunner.query(`DROP TABLE "user_tip"`, undefined);
    await queryRunner.query(`ALTER TABLE "temporary_user_tip" RENAME TO "user_tip"`, undefined);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`ALTER TABLE "user_tip" RENAME TO "temporary_user_tip"`, undefined);
    await queryRunner.query(`CREATE TABLE "user_tip" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "amount" float NOT NULL, "currency" varchar NOT NULL, "message" text NOT NULL DEFAULT (''), "tippedAt" bigint NOT NULL DEFAULT (0), "sortAmount" float NOT NULL, "userUserId" integer, CONSTRAINT "FK_36683fb221201263b38344a9880" FOREIGN KEY ("userUserId") REFERENCES "user" ("userId") ON DELETE CASCADE ON UPDATE CASCADE)`, undefined);
    await queryRunner.query(`INSERT INTO "user_tip"("id", "amount", "currency", "message", "tippedAt", "sortAmount", "userUserId") SELECT "id", "amount", "currency", "message", "tippedAt", "sortAmount", "userUserId" FROM "temporary_user_tip"`, undefined);
    await queryRunner.query(`DROP TABLE "temporary_user_tip"`, undefined);
    await queryRunner.query(`ALTER TABLE "twitch_stats" RENAME TO "temporary_twitch_stats"`, undefined);
    await queryRunner.query(`CREATE TABLE "twitch_stats" ("whenOnline" bigint PRIMARY KEY NOT NULL, "currentViewers" integer NOT NULL DEFAULT (0), "currentSubscribers" integer NOT NULL DEFAULT (0), "currentBits" bigint NOT NULL, "currentTips" float NOT NULL, "chatMessages" bigint NOT NULL, "currentFollowers" integer NOT NULL DEFAULT (0), "currentViews" integer NOT NULL DEFAULT (0), "maxViewers" integer NOT NULL DEFAULT (0), "currentHosts" integer NOT NULL DEFAULT (0), "newChatters" integer NOT NULL DEFAULT (0), "currentWatched" bigint NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "twitch_stats"("whenOnline", "currentViewers", "currentSubscribers", "currentBits", "currentTips", "chatMessages", "currentFollowers", "currentViews", "maxViewers", "currentHosts", "newChatters", "currentWatched") SELECT "whenOnline", "currentViewers", "currentSubscribers", "currentBits", "currentTips", "chatMessages", "currentFollowers", "currentViews", "maxViewers", "currentHosts", "newChatters", "currentWatched" FROM "temporary_twitch_stats"`, undefined);
    await queryRunner.query(`DROP TABLE "temporary_twitch_stats"`, undefined);
    await queryRunner.query(`ALTER TABLE "song_request" RENAME TO "temporary_song_request"`, undefined);
    await queryRunner.query(`CREATE TABLE "song_request" ("videoId" varchar NOT NULL, "addedAt" bigint NOT NULL DEFAULT (0), "title" varchar NOT NULL, "loudness" float NOT NULL, "length" integer NOT NULL, "username" varchar NOT NULL, "id" varchar PRIMARY KEY NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "song_request"("videoId", "addedAt", "title", "loudness", "length", "username", "id") SELECT "videoId", "addedAt", "title", "loudness", "length", "username", "id" FROM "temporary_song_request"`, undefined);
    await queryRunner.query(`DROP TABLE "temporary_song_request"`, undefined);
    await queryRunner.query(`ALTER TABLE "song_playlist" RENAME TO "temporary_song_playlist"`, undefined);
    await queryRunner.query(`CREATE TABLE "song_playlist" ("videoId" varchar PRIMARY KEY NOT NULL, "lastPlayedAt" bigint NOT NULL DEFAULT (0), "seed" float NOT NULL, "title" varchar NOT NULL, "loudness" float NOT NULL, "length" integer NOT NULL, "forceVolume" boolean NOT NULL DEFAULT (0), "volume" integer NOT NULL, "startTime" integer NOT NULL, "endTime" integer NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "song_playlist"("videoId", "lastPlayedAt", "seed", "title", "loudness", "length", "forceVolume", "volume", "startTime", "endTime") SELECT "videoId", "lastPlayedAt", "seed", "title", "loudness", "length", "forceVolume", "volume", "startTime", "endTime" FROM "temporary_song_playlist"`, undefined);
    await queryRunner.query(`DROP TABLE "temporary_song_playlist"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_301758e0e3108fc902d5436527"`, undefined);
    await queryRunner.query(`ALTER TABLE "how_long_to_beat_game" RENAME TO "temporary_how_long_to_beat_game"`, undefined);
    await queryRunner.query(`CREATE TABLE "how_long_to_beat_game" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "game" varchar NOT NULL, "startedAt" bigint NOT NULL DEFAULT (0), "isFinishedMain" boolean NOT NULL, "isFinishedCompletionist" boolean NOT NULL, "timeToBeatMain" bigint NOT NULL DEFAULT (0), "timeToBeatCompletionist" bigint NOT NULL DEFAULT (0), "gameplayMain" float NOT NULL DEFAULT (0), "gameplayCompletionist" float NOT NULL DEFAULT (0), "imageUrl" varchar NOT NULL)`, undefined);
    await queryRunner.query(`INSERT INTO "how_long_to_beat_game"("id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl") SELECT "id", "game", "startedAt", "isFinishedMain", "isFinishedCompletionist", "timeToBeatMain", "timeToBeatCompletionist", "gameplayMain", "gameplayCompletionist", "imageUrl" FROM "temporary_how_long_to_beat_game"`, undefined);
    await queryRunner.query(`DROP TABLE "temporary_how_long_to_beat_game"`, undefined);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_301758e0e3108fc902d5436527" ON "how_long_to_beat_game" ("game") `, undefined);
    await queryRunner.query(`DROP INDEX "IDX_a1a6bd23cb8ef7ddf921f54c0b"`, undefined);
    await queryRunner.query(`ALTER TABLE "goal" RENAME TO "temporary_goal"`, undefined);
    await queryRunner.query(`CREATE TABLE "goal" ("id" varchar PRIMARY KEY NOT NULL, "groupId" varchar, "name" varchar NOT NULL, "type" varchar(20) NOT NULL, "countBitsAsTips" boolean NOT NULL, "display" varchar(20) NOT NULL, "timestamp" bigint NOT NULL DEFAULT (0), "goalAmount" float NOT NULL DEFAULT (0), "currentAmount" float NOT NULL DEFAULT (0), "endAfter" varchar NOT NULL, "endAfterIgnore" boolean NOT NULL, "customizationBar" text NOT NULL, "customizationFont" text NOT NULL, "customizationHtml" text NOT NULL, "customizationJs" text NOT NULL, "customizationCss" text NOT NULL, CONSTRAINT "FK_a1a6bd23cb8ef7ddf921f54c0bb" FOREIGN KEY ("groupId") REFERENCES "goal_group" ("id") ON DELETE CASCADE ON UPDATE CASCADE)`, undefined);
    await queryRunner.query(`INSERT INTO "goal"("id", "groupId", "name", "type", "countBitsAsTips", "display", "timestamp", "goalAmount", "currentAmount", "endAfter", "endAfterIgnore", "customizationBar", "customizationFont", "customizationHtml", "customizationJs", "customizationCss") SELECT "id", "groupId", "name", "type", "countBitsAsTips", "display", "timestamp", "goalAmount", "currentAmount", "endAfter", "endAfterIgnore", "customizationBar", "customizationFont", "customizationHtml", "customizationJs", "customizationCss" FROM "temporary_goal"`, undefined);
    await queryRunner.query(`DROP TABLE "temporary_goal"`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_a1a6bd23cb8ef7ddf921f54c0b" ON "goal" ("groupId") `, undefined);
  }

}
