name: Generic tests

concurrency:
  group: generic-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: All test should be run - tests are not containing describe.only
      run: |
          if ! grep -r -l 'describe.only' ./test/; then
            exit 0
          else
            exit 1
          fi;
    - name: install node LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        check-latest: true
    - name: Install eslint and dependencies
      run: |
        NODE_MODULES_DIR=./node_modules make dependencies
    - name: Run eslint
      run: ENV=development make eslint
    - name: Run jsonlint
      run: ENV=development make jsonlint
  fullbuild:
    name: Make test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - id: log
      name: Load commit message for skip test check
      run: echo "MESSAGE=$(git log --no-merges -1 --pretty=format:%s%b)" >> $GITHUB_OUTPUT
    - name: install node LTS
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        check-latest: true
    - name: Install all dependencies and build everything
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: ENV=development NODE_MODULES_DIR=./node_modules make